luckyframework/avram

- spec/bool_criteria_spec.cr
- spec/criteria_spec.cr
- spec/model_spec.cr
- spec/preloading_spec.cr
- spec/query_associations_spec.cr
- spec/query_builder_spec.cr
- spec/query_spec.cr
- spec/string_criteria_spec.cr
- spec/time_criteria_spec.cr
- spec/where_spec.cr
- src/avram/base_query_template.cr
- src/avram/criteria.cr
- src/avram/query_builder.cr
- src/avram/validations.cr
- src/avram/where.cr
Continuation/migration of https://github.com/luckyframework/lucky_record/pull/289. See there for details.
Closes #38.
> Fix comparisons to `nil` in queries & make such queries explicit

- spec/form_spec.cr
- spec/virtual_form_spec.cr
- src/avram/form.cr
- src/avram/param_key_override.cr
- src/avram/virtual_form.cr
Closes #70
This allows someone to customize what param key is used. Especially
helpful with JSON APIs where you care more about what the key is.
For HTML forms it doesn't really matter since the end user never really
uses them.
> Add Form#param_key

- spec/form_spec.cr
- src/avram/errors.cr
- src/avram/form.cr
Crystal has issues with Generics and downcasting. Let's just add the
errors to the form and make it non-generic.
> Remove generic arg from InvalidFormError

- spec/connection_spec.cr
- src/avram/connection.cr
- src/avram/errors.cr
- src/avram/repo.cr
closes #81 (though, this is an alternative to doing that)
Prior to this, you'd get a `DB::ConnectionRefused error` as well as some `PQ` related errors. Now you get a nice error message that helps to explain what went wrong, and possible ways to fix it.
> Raise pretty error message when connection fails

- spec/box_spec.cr
- spec/support/base_box.cr
- spec/support/boxes/tag_box.cr
- src/avram/box.cr
_Note: just adding this because I ran into it while developing and it was about as easy to impliment it as it was to make an issue. Feel free to push back 🙂_
Unique values are a good thing and application developers should use
them. However, testing with unique values can be a pain since you need
to create a new value explicitly in tests instead of using a default
value via a Box.
This makes sequences (some code that I found in the Avram tests)
included by default in every box. This seems like a thing that users
shouldn't have to build into every app themselves.
> Add sequence to Avram::Box

- spec/migrator/alter_table_statement_spec.cr
- src/avram/migrator/column_default_helpers.cr
Adding a simple UUID column failed with "undefined method add_column"
because the UUID type was not recognized for default values.
A static default for UUIDs is kind of ... unintuitive ... anyway, but this gets me going for now.
What I think should be the next step is to maybe allow passing a block or something to fill_existing_with: ... in order to get a different value for each entry in the db. But I see that as a separate task to tackle?
(Storing a UUID in postgres can be done in UUID, but generating one requires an extension, so I opted out of something like DEFAULT generate_uuid_v1()).
> Allow adding UUID columns (that are not associations)

- spec/nested_save_operation_spec.cr
- spec/operation_needs_spec.cr
- spec/preloading_spec.cr
- spec/save_operation_callbacks_spec.cr
- spec/save_operation_spec.cr
- spec/transaction_spec.cr
- spec/type_extension_spec.cr
- spec/validations_spec.cr
- spec/virtual_operation_spec.cr
- spec/virtual_spec.cr
- src/avram/box.cr
- src/avram/errors.cr
- src/avram/form_name.cr
- src/avram/mark_as_failed.cr
- src/avram/model.cr
- src/avram/nested_save_operation.cr
- src/avram/save_operation.cr
- src/avram/save_operation_errors.cr
- src/avram/save_operation_template.cr
- src/avram/validations.cr
- src/avram/virtual_operation.cr
Closes #30
This will require changes to LuckyCLI and Lucky. We can merge this then fix those
These changes are big so rather than deprecating and maintaining tons of code for a release or two, I think we need to pull off the bandaid and make the switch. It's mostly renaming so I think this should be easy for people to upgrade anyway
> Rename Form -> SaveOperation

- spec/query_spec.cr
- src/avram/queryable.cr
Make it match the ordering that the `last?` method uses. Fixes #115.
> Ensure proper ordering in the `first?` method

- db/migrations/20190702125912_create_menu_options.cr
- spec/migrator/create_table_statement_spec.cr
- spec/query_spec.cr
- spec/support/boxes/menu_option_box.cr
- spec/support/menu_option.cr
- spec/type_extension_spec.cr
- src/avram/blank_extensions.cr
- src/avram/charms/int16_extensions.cr
- src/avram/migrator/columns/int16_column.cr
- src/avram/migrator/columns/primary_keys/int16_primary_key.cr
This adds in support for Int16 for columns (`smallint`), and as a primary key using `smallserial`.
closes #2 
closes #130
> Full support for Int16

- spec/associations_spec.cr
- spec/support/admin.cr
- spec/support/comment.cr
- spec/support/employee.cr
- spec/support/line_item_product.cr
- spec/support/manager.cr
- spec/support/post.cr
- spec/support/price.cr
- spec/support/sign_in_credential.cr
- spec/support/user.cr
- src/avram/associations.cr
- src/avram/base_query_template.cr
- src/avram/model.cr
This improves an issue where previously you had to require associations.
Now we don't because we no longer resolve the type in the macro.
The one downside is that if you have a table name that is not the
default pluralized snake case, you will need to provide it in
`belongs_to`. I think this is a great tradeoff since the require issue
is annoying and causes a lot of issues. Also most people use those
defaults so it should be fine.
> Table name is guessed. No requires required

- script/test
- src/avram/migrator/runner.cr
- src/avram/tasks/db/rollback_to.cr
Wow, that was easier than I thought!
But I don't understand the specs well enough to be sure that these tasks don't have specs. Is there somewhere I'm missing that a task spec belongs?
Also you'll notice that I changed the messaging a bit in the test script. Since I put this before `rollback_all` I wanted to make sure I could visually compare (assuming that's our test method) what the message says we are rolling back to vs what actually got rolled back.
If this goes in, I'll be happy to update the docs (over on the lucky webpage right?). The doc should say something like "rollback_to <last stable integer timestamp>" and make it clear that we are *not* rolling back the migration named in the time stamp, we are rolling back *to* the state that that migration provided.
> add rollback_to feature

- spec/query_spec.cr
- src/avram/query.cr
- src/avram/repo.cr
fixes #110
I also documented the Repo.truncate just so we don't get the two confused.
> renamed destroy_all to truncate.

- script/test
- shard.yml
- src/avram/migrator/runner.cr
- src/avram/tasks/db/migrations_status.cr
This is my first attempt at a contribution to Lucky and pretty much my first time writing Crystal code, so any / all feedback is super appreciated.
I took at a stab at adding the `lucky db.migrations.status` task from https://github.com/luckyframework/avram/issues/126
A few things to note:
- I added the `shell-table` shard as a dependency to help format the output.
- The `shell-table` shard is pointing to a branch on the fork at luckyframework. I didn't have a good reason to do this other than that's the version lucky itself is using (https://github.com/luckyframework/lucky/blob/32db2b499227541ab43b5927bf88e1b95a3e53d8/shard.yml#L47-L49). Happy to update this.
- It doesn't look like there are existing tests for CLI tasks so I didn't add any, but please point me in the right direction if …
> Add lucky db.migrations.status CLI task

- spec/model_spec.cr
- src/avram/model.cr
- src/run_macros/infer_table_name.cr
> Infer namespaced models

- spec/type_extensions/time_spec.cr
- src/avram.cr
- src/avram/charms/time_extensions.cr
> Handle more time formats and allow custom formats

- spec/define_attribute_spec.cr
- spec/nested_save_operation_spec.cr
- spec/operation_needs_spec.cr
- spec/operation_spec.cr
- spec/save_operation_callbacks_spec.cr
- spec/save_operation_spec.cr
- spec/spec_helper.cr
- spec/type_extension_spec.cr
- spec/validations_spec.cr
- src/avram/callbacks.cr
- src/avram/database_validations.cr
- src/avram/nested_save_operation.cr
- src/avram/operation.cr
- src/avram/param_key_override.cr
- src/avram/save_operation.cr
- src/avram/save_operation_template.cr
- src/avram/validations.cr
This requires more work, refactoring, and possible extracting to another shard for `LuckyOperation` or something. Can be figured out later
> Improve callbacks and operation setup and validation 

- shard.yml
Part of https://github.com/luckyframework/lucky/issues/806
This PR locks down 3rd party shards to specific versions. When running `shards update`, there's potential (especially right after a new crystal version is released) that everything breaks. By locking these down, we ensure that our current version plays nicely together.
These current shard versions are what is specified in our `shard.lock` currently. So we know that these versions all play nice together.
> locking down 3rd party shards. 

- spec/spec_helper.cr
- spec/tasks/db_verify_connection_spec.cr
- src/avram/tasks/db/verify_connection.cr
Phase 2 of https://github.com/luckyframework/lucky_cli/pull/376
Fixes https://github.com/luckyframework/avram/issues/166
This PR adds a new task to verify that avram can actually connect to the DB based on your credentials.
> Add lucky db.verify_connection task

- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
Fixes #111 
Based on how rails works, when you run the `delete_all` method, it'll return an integer, so it's going to be the last thing you run in your query. You can chain all your wheres like normal though.
> Adding new delete_all query method to remove records based on query

- db/migrations/20190723233130_create_polymorphic_belongs_to.cr
- script/test
- spec/model_spec.cr
- spec/polymorphic_spec.cr
- spec/support/base_model.cr
- spec/validations_spec.cr
- src/avram/model.cr
- src/avram/polymorphic.cr
- src/avram/tasks/gen/migration.ecr
- src/avram/validations.cr
> Polymorphic helpers

- spec/query_associations_spec.cr
- src/avram/associations/has_many.cr
- src/avram/base_query_template.cr
Closes #171
Another issue has been opened for ensuring joins and wheres are unique before generating a statement https://github.com/luckyframework/avram/issues/175. That should make this a lot more reliable
> Make querying associations more explicit

- spec/polymorphic_spec.cr
- src/avram/polymorphic.cr
Closes #178
It also has this underneath:
Which indicates which type needs  to be nil. This error is a bit tricky now with Crystal 0.29 but in 0.30 it  will be  just the macro line that has the issue, which means this should be pretty easy to find in the printed error message
> Ensure polymorphic belongs to are nilable

- spec/query_builder/merge_spec.cr
- spec/query_spec.cr
- src/avram/query_builder.cr
Fixes #189 
This allows us to order on a column in a joined table:
```crystal
Post::BaseQuery.new.where_comments(Comment::BaseQuery.new.created_at.asc_order)
```
> merge in orders for queries

- script/precompile_tasks
`script/precompile_tasks` was failing if Avram was installed as a dependency of a project whose path contains a space, such as a subdirectory of an iCloud Drive folder (which is usually `/Users/$USER/Library/Mobile Documents/com~apple~CloudDocs/`), since the shell was treating the space as a separator. This commit tells the shell to avoid treating spaces in the current directory's path as an argument separator.
> Allow for spaces in pwd output in precompile_tasks

- spec/box_spec.cr
- src/avram/box.cr
Fixes #199
Also added method overload for accepting a block. 
Before this PR, using `Box.create_pair` always returned `nil`, and there was no way to customize the boxes being created. Now it returns `[model, model]`. You can also pass a block in to customize it:
```crystal
users = UserBox.create_pair do |user_box|
user_box.name(user_box.sequence("Jeremy"))
end
users.first.name #=> Jeremy-1
users.last.name #=> Jeremy-2
```
> update Box.create_pair to now return an array of the instance. 

- spec/migrator/alter_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
In #121 we changed our primary keys from `Int32` to `Int64` but I believe we forgot to update the alter table migration statements to use Int64 as the default primary key type. This causes errors like:
```
PG::ResultSet#read returned a Int32. A (Int64 | Nil) was expected. (Exception)
```
or the very similar
```
PG::ResultSet#read returned a Int32. A Int64 was expected. (Exception)
```
> add_belongs_to uses bigint in AlterTable statements

- spec/query_spec.cr
- src/avram/queryable.cr
Fixes #220
This adds a copy for the preloads on to the new cloned object.
Note: One issue is that the spec fails on this line
```
products.first.line_items.first.price.as(Price).in_cents.should eq(500)
```
With the error: 
> price for LineItem must be preloaded with 'preload_price' (Avram::LazyLoadError)
I'm not sure why since I am calling `preload_price`. Could this be an unrelated bug?
> ensure preloads get copied over on clone. 

- src/avram/save_operation_template.cr
I ran into this when upgrading to lucky 0.17. Not yet having made the necessary changes switching forms to operations, I got the unwieldly
```
Error: undefined macro variable 'type'
```
This is due to mistakenly using normal string interpolation where we instead want the macro argument to be interpolated into the error message. This then shows the proper error message
```
Error: BaseForm has been renamed to SaveOperation. Please inherit from Post::SaveOperation.
```
> Fix macro string interpolation

- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/avram/criteria.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
Fixes #193 
We have `select_count` currently, but maybe that needs to become aware if there's some grouping?
> Add in GROUP BY querying

- src/avram/callbacks.cr
> Add compile-time error to catch use of before in SaveOperation.

- src/avram/schema_enforcer.cr
There was a bug where Crystal could not accurately determine the type
of the Model when there were no models in Avram::SchemaEnforcer.
The simple fix is to not generated the code if there are no models.
> Only enforce models if presents

- spec/spec_helper.cr
Some specs access to another database that can't be overridden as the main DB.
> Allow overriding backup database via BACKUP_DATABASE_URL

- spec/model_spec.cr
- src/avram/model.cr
Avram supports Int64 | Int32 | Int16 | UUID as primary keys. Current implementation does not escape UUID (as it's basically a string), this causes an exception.
This pull request fixes that issue.
> Allow record deletion when primary key is UUID

- spec/migrator/create_table_statement_spec.cr
- src/avram/migrator/columns/base.cr
This fixes an issue with supplying an empty array as a default.
It also fixes the formatting of of the array to match what postgres expects.
> Empty array default fix

- spec/query_spec.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
Fixes #248
This adds `reset_limit` and `reset_offset` which can be combined to make your own `reset_pagination` if you need. This is useful for when you have a paginated collection, but you need to get a total count without the limit and offset.
> adding a reset_limit and reset_offset. 

- spec/save_operation_callbacks_spec.cr
- src/avram/callbacks.cr
- src/avram/operation.cr
- src/avram/save_operation.cr
Fixes #265
Fixes #258 
Supersedes #261 
Since `previous_def` doesn't bubble up, we add in a call to `super` when no other methods are there. This will bubble up and catches the built-in validation callbacks, and setting the id for UUID primary key.
> updating SaveOperation callbacks to also call the super callbacks

- Dockerfile
1. Docker layers once created are immutable.    Clean up, therefore, must happen in the same layer. 
2. ADD is for archives, though semantically works like COPY, it's the wrong tool.  
This PR fixes both of those plus moves stuff around. Avoid invalidating the cache as long as possible.
Closes #272
> Small dockerfile fixes

- spec/query_spec.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
Fixes #239
This adds a new `to_prepared_sql` method to query objects. When debugging, or logging, you might use `to_sql` which returns an array where the first element is the SQL string, and the second is an array of the WHERE args. In some cases when debugging, you may want to copy this SQL and run it directly in psql to see the result. With larger and more complex SQL (especially with arrays and json), this becomes very difficult. You have to know what a postgres json or array object looks like, and how to manually convert it.
This new `to_prepared_sql` method takes your args, converts them to PG, then injects them in to the SQL string so you have a straight copy/paste string that can be run directly in postgres.
> Adds new to_prepared_sql method 

- .travis.yml
- README.md
- script/docs
Generates docs (`crystal docs`) for Travis CI
Continuation of: https://github.com/luckyframework/lucky/issues/988
On any commit into `master`, this will auto-deploy documentation generated from `crystal docs` on Github Pages.
**Travis CI config needs to be updated to include GITHUB_TOKEN environment variable**
The GITHUB_TOKEN, which is a [github personal access token](https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line), only needs the `public_repo` scope.
> Generate docs for CI

- spec/query_spec.cr
- src/avram/query_builder.cr
Fixes #284
I had to take off the private and break out the methods so that way I had access to the distincts on the query being merged in.
> Fixing clone for distincts

- db/migrations/20170127143149_create_users.cr
- spec/model_spec.cr
- spec/query_spec.cr
- spec/support/boxes/user_box.cr
- spec/support/user.cr
- src/avram/model.cr
As discussed in #288, this PR adds the `method_name?` variant for boolean columns, and includes a boolean column in the specs as well.
> Add boolean getter for boolean columns.

- spec/attribute_spec.cr
- spec/json_column_spec.cr
- spec/polymorphic_spec.cr
- spec/save_operation_spec.cr
- src/avram/attribute.cr
- src/avram/save_operation.cr
Adds:
- `#changed?` with optional `from:` and `to:` arguments
- `#changes`
- `#original_value`
> Add Attribute#changed? with to: and from: options

- spec/validations_spec.cr
- src/avram/validations.cr
As suggested in #293, this PR adds an `allow_nil` option for `validate_size_of` and `validate_inclusion_of`.
> Allow nil on size and inclusion validations.

- db/migrations/20170127143149_create_users.cr
- spec/model_spec.cr
- spec/query_spec.cr
- spec/support/boxes/user_box.cr
- spec/support/user.cr
- src/avram/charms/float64_extensions.cr
- src/avram/charms/int16_extensions.cr
- src/avram/charms/int32_extensions.cr
- src/avram/charms/int64_extensions.cr
- src/avram/criteria.cr
Currently select_sum only works for Int32 and Int16 columns. The fix allows select_sum for Int16, Int32, Int62, and Float64 columns.
This also fixes an issue when the result is nil which was failing before.
This change also ads a `select_sum!` method that returns 0 of the correct type instead of nil if there are no records.
See issue #292
> Fix Criteria#select_sum

- spec/query_associations_spec.cr
- spec/query_spec.cr
- src/avram/associations/has_one.cr
- src/avram/base_query_template.cr
Fixes #223
This fixes 2 main issues with the `has_one`:
* Using `has_one` when your model is namespaced
* Doing a join query with has_one from both sides of the association
> Fixing query with has_one 

- db/migrations/20170127143149_create_users.cr
- spec/model_spec.cr
- spec/query_spec.cr
- spec/support/boxes/user_box.cr
- spec/support/user.cr
- src/avram/criteria.cr
Addresses issues with aggregate queries
See #292, #304, and #287
> Fix aggregates

- db/migrations/20200227193531_create_virgin.cr
- spec/box_spec.cr
- spec/support/boxes/virgin_box.cr
- spec/support/virgin.cr
Added a model with just the default columns, its box and a spec to verify the box is created properly. With the old code it failed, with the new code, which is already in master, all specs pass. So this confirms the fix for #309.
> Specs for empty boxes

- spec/define_attribute_spec.cr
- spec/operation_needs_spec.cr
- spec/save_operation_callbacks_spec.cr
- spec/save_operation_spec.cr
- spec/transaction_spec.cr
- spec/type_extension_spec.cr
- src/avram/needy_initializer_and_save_methods.cr
- src/avram/save_operation.cr
PR for #204 
**BREAKING CHANGE**
**Reasoning:**
> The main problem we're trying to solve with disallowing hash directly is that people use it without realizing the alternative and end up losing type-safety (and making their apps more complex because they try to merge things together)
> Disallow raw Hash in SaveOperation

- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/avram/criteria.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
This will reset where for a specific column. Initially, you could also call `query.reset_where` without a block, which would reset all where clauses. But I removed that because it could lead to unexpected/unwanted results.
Closes #319
> Added reset_where method for specific columns.

- spec/spec_helper.cr
- src/avram.cr
- src/avram/pool_statement_logging.cr
Ran into this while working on #322. I wanted to see the failed query.
The downside to this is that if you happen to rescue a `PQ::PQError` later in your app the failed query will still be logged. I think this is acceptable though since I can't think of a reason not to.
I've added a setting though just in case you don't want to log failed queries
> Log failed queries

- spec/migrator/alter_table_statement_spec.cr
- spec/migrator/migration_spec.cr
- src/avram/migrator/alter_table_statement.cr
Fixes #278
Currently, this fails when your table already has data in it. If your table is empty, then it works fine.
```crystal
def migrate
alter table_for(User) do
add name : String, fill_existing_with: "anonymous"
end
end
```
What happens is postgres goes to add the column and sees that it's `NOT NULL`, but we don't fill the "anonymous" string in until after the column exists. So this would give you a NULL value in the new column. That makes postgres sad. 
This PR fixes that by looking to see that there's a `fill_existing_with`, and it's not equal to `:nothing`, then it makes the column temporarily nullable. Then after the column is added, we update it afterward to make it `NOT NULL`.
> Fix fill_existing_with when there's already data existing

- shard.yml
We don't actually need the `crystal-db` in here since `crystal-pg` already has that as a dependency. This lets us stay in line with what ever pg uses. That way we don't accidentally forget to update db, or have them out of sync. 
This also updates crystal-pg to latest which just has better crystal 0.34 support.
> Update for lastet crystal-pg support

- spec/query_spec.cr
- src/avram/queryable.cr
Fixes #297
In a more complex case, postgres won't return any value when trying to do a count. This causes DB to just raise an exception instead of returning 0.
> Fix select_count edge case of raising an exception

- spec/migrator/alter_extension_statement_spec.cr
- spec/migrator/create_extension_statement_spec.cr
- spec/migrator/drop_extension_statement_spec.cr
- src/avram/migrator/alter_extension_statement.cr
- src/avram/migrator/create_extension_statement.cr
- src/avram/migrator/drop_extension_statement.cr
- src/avram/migrator/statement_helpers.cr
- src/avram/save_operation.cr
This PR will be needed to do #122 and #188 
This adds in helper methods for enabling and disabling extensions.
```crystal
enable_extension "uuid-ossp"
disable_extension "uuid-ossp"
update_extension "hstore", to: "2.0"
```
> Adding in extension support

- db/migrations/20200324211956_create_issue.cr
- spec/support/boxes/issue_box.cr
- spec/support/issue.cr
- spec/type_extensions/enum_spec.cr
- src/avram/charms/enum.cr
- src/avram/charms/enum_extensions.cr
Got help a bit from @paulcsmith with this.
It is a bit hacky. 
Instead of using enum Status, you use this macro.
Like this:
```
class Issue <  BaseModel
avram_enum Status do
Opened = 1
end
```
and for the int32 type add `Status` as type instead.
It shall now work, but with some changes in create and update:
```
status: Issue::Status.new(:opened)
```
No tests as I am not sure how you would like to test this macro?
> added enum support

- db/migrations/20200513065134_test_rename_columns.cr
- spec/migrator/alter_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
A proposal as suggested in #365. This makes me think about picking up #321 as well, since the same is true.
> Add rename and rename_belongs_to for migrations.

- spec/migrator/create_index_statement_spec.cr
- spec/migrator/drop_index_statement_spec.cr
- src/avram/migrator/create_index_statement.cr
- src/avram/migrator/drop_index_statement.cr
- src/avram/migrator/statement_helpers.cr
I suggest adding the ability to set custom names for the index.
Postgresql has a length limit on the index name. 
These two indexes will have the same name:
`create_index :items, [:column1, :column2, :column3, :column4, :column5, :column6, :column7, :column8]`
`create_index :items, [:column1, :column2, :column3, :column4, :column5, :column6, :column7, :column8, :column9, :column10]`
The name will be "items_column1_column2_column3_column4_column5_column6_column7_c". So when creating the second index, an error occurs:
`relation "items_column1_column2_column3_column4_column5_column6_column7_c" already exists (Exception)`
In this case, we can set a custom name for the second index and avoid the error.
`create_index :items, [:column1, :column2, :column3, :column4, :column5, :column6, :column7, …
> Custom name for index

- spec/tasks/db_create_spec.cr
- src/avram/errors.cr
- src/avram/migrator/runner.cr
- src/avram/tasks/db/create.cr
Fixes #417 
It turns out that if your postgres username is the same as your OS username, and you don't pass a database name to `psql`, then it tries to assume you want to connect to a database of that name. If that database name doesn't exist (because it really shouldn't), then it fails. This also means that `./script/setup` fails. 
It's ok anyway, because the `create_db` method already throws errors based on connection. In this PR I'm moving those error messages to Error classes as well. This keeps all of these errors in a single location.
> Reverting the db.create task connection test

- CODE_OF_CONDUCT.md
- script/test
- src/avram/define_attribute.cr
Based on the same PR to Lucky: https://github.com/luckyframework/lucky/pull/1223.
Removed trailing spaces in project files:
- CODE_OF_CONDUCT.md
- script/test
- src/avram/define_attribute.cr
> Removed trailing spaces in project files

- spec/migrator/create_function_statement_spec.cr
- spec/migrator/drop_function_statement_spec.cr
- src/avram/migrator/create_function_statement.cr
- src/avram/migrator/drop_function_statement.cr
- src/avram/migrator/statement_helpers.cr
This is a precursor to #393 
This PR adds the ability to define postgres functions. By default I have made these trigger functions because I feel those may be the most common. A trigger function is a function that can only be called from a trigger. A trigger is just basically a callback in postgres. 
Now, postgres functions can get super complicated real quick. There's a ton of possible options you can have, and all kinds of return types. What this PR does is gives you the ability to do some simple functions by providing you with some boilerplate. Beyond the simple ones you may need you can always use the `execute()` method in your migrations to hand roll your own complex functions.
The ability to define triggers will come in another PR.
```crystal
def migrate
create_function …
```
> Adding define functions

- spec/migrator/create_trigger_statement_spec.cr
- spec/migrator/drop_trigger_statement_spec.cr
- spec/migrator/migration_spec.cr
- src/avram/migrator/create_trigger_statement.cr
- src/avram/migrator/drop_trigger_statement.cr
- src/avram/migrator/statement_helpers.cr
This is a stepping stone to closing out 
https://github.com/luckyframework/avram/issues/337
https://github.com/luckyframework/avram/issues/393
This PR introduces the ability to set simple triggers. As with most Postgres things, it can get super hairy, so if you need something complex, it's best to hop out of Avram anyway. These should cover the 90% use case though.
This create a BEFORE UPDATE trigger called "trigger_set_timestamp" that will call the "set_timestamp()" function
```crystal
create_trigger table_for(User), "set_timestamp"
```
You can create a trigger for BEFORE/AFTER and on INSERT/UPDATE/DELETE by passing some options:
```crystal
create_function "update_counts", <<-SQL
NEW.some_count = OLD.some_count + 1
RETURN NEW;
SQL
create_trigger :users, "update_counts", callback: :after, …
```
> Adding new triggers feature to generate postgres triggers.

- spec/migrator/alter_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
Fixes #17 
Fixes #22 
Let me know if this needs to do more.
> Adding support for fill_existing_with on add_belongs_to

- spec/save_operation_spec.cr
- src/avram/save_operation.cr
Fixes #447
Fixes #20 
If you pass a permitted column that's nilable through params as an empty string, then it will fail to cast that like in the case of `Time?` being parsed https://github.com/luckyframework/avram/blob/master/src/avram/charms/time_extensions.cr#L27. So in this case, if the type is nilable, and we send an empty value, just return nil instead of assigning a value. 
One case to note here that we may need to handle separately would be if you defined a `String?` and were ok with this being an empty string. In this case, you should just make your column NOT nilable, but as of right now we don't tell you that.
> Fixed passing an empty string to a nilable type through params

- spec/array_column_spec.cr
- spec/query_builder_spec.cr
- spec/query_spec.cr
- spec/support/bucket_query.cr
- src/avram/base_query_template.cr
- src/avram/between_criteria.cr
- src/avram/criteria.cr
- src/avram/join.cr
- src/avram/order_by.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
- src/avram/where.cr
I would like some feedback on if this a valid path forward or if there is a better way.
There are 2 breaking changes in this PR:
- The clone method on QueryBuilder no longer takes an argument.
- queries are no longer mutated, so you need to chain your criteria calls.
Fixes #194 
Fixes #195
Fixes #242
> Clone instead of mutate when changing query criteria

- src/avram/model.cr
Pointed out in [this issue comment](https://github.com/luckyframework/avram/issues/6#issuecomment-515215447)
If a model uses `skip_default_columns`, they are required to call `primary_key` in the `table` block. If they forget, the error is cryptic. This updates the process to actually check for a primary key and provide a more clear error.
```
Showing last frame. Use --error-trace for full trace.
In src/avram/model.cr:170:30
170 | primary_key_type: {{ PRIMARY_KEY_TYPE }},
^
Error: undefined constant PRIMARY_KEY_TYPE
```
```
Showing last frame. Use --error-trace for full trace.
There was a problem expanding macro 'table'
Code in spec/support/line_item_product.cr:4:3
4 | table :line_items_products do
^
Called macro defined in src/avram/model.cr:112:3
112 | macro table(table_name = nil) …
```
> Provide better error when primary key is missing

- src/avram/base_query_template.cr
- src/avram/primary_key_queryable.cr
- src/avram/queryable.cr
Related to #453 
If we want to support database views in the future, one step in getting there is removing the requirement of the database table having a primary key.
When the time comes to allow not setting a primary key, the `BaseQueryTemplate` not include `PrimaryKeyQueryable` which will remove any ability to query by the primary key for that model.
> Extract PrimaryKeyQueryable from Queryable

- db/migrations/20190712145900_create_buckets_with_array_types.cr
- spec/array_column_spec.cr
- spec/migrator/alter_table_statement_spec.cr
- spec/support/bucket.cr
- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/create_table_statement.cr
- src/avram/model.cr
Fixes #470 
There are a couple of bugs that are fixed by these changes:
- You could not add an optional array column in a migration
- Optional array fields on models were not converted from database queries correctly
- Adding an array column to a table was adding "NOT NULL" to the add column sql statement even if it was not intended
> Add support for optional arrays

- spec/type_extensions/enum_spec.cr
- src/avram/charms/enum_extensions.cr
making it possible to get int and the string directly, good for showing the enum on pages and such.
Not it will return class instance on `to_s` and not work at all on `to_i`
now it will return say `Ongoing` on to_s and `0` on to_i
not sure if maybe this will work instead:
```
delegate :to_s, :to_i, to: @enum
```
I feel it is a personal taste that feels best. I can change to that if you want.
> overwrite to_s and to_i for Enums

- shard.yml
- spec/model_spec.cr
- src/avram/charms/uuid_extensions.cr
Fixes #476
With the latest crystal-db and pg shards, UUID is supported more natively. This means that UUID columns can now be treated as UUID and not be faked with String.
> Update to latest PG and DB shards.

- spec/query_builder/merge_spec.cr
- spec/query_builder_spec.cr
- spec/query_spec.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
- src/avram/where.cr
Fixes #459
`Avram::Where::Raw` and `Avram::Where::SqlClause` did not have overlapping ancestors so they were stored in separate lists in `Avram::QueryBuilder` and had different APIs. When the sql string was put together, raw wheres were appended to the where clause. When "OR" support is added, this will no longer be acceptable.
It simplifies the API to have them be used in the same way. This adds a common ancestor of `Avram::Where::Condition` that has the one method of `#prepare`. The only problem of doing this is that `SqlClause`s where being passed a placeholder string that had an incrementing number. Rather than keeping with the push style and checking which types were save to give the placeholder to, I switched the where conditions to take in a supplier of those placeholders so that …
> Represent wheres and raw wheres in the same way

- spec/query_associations_spec.cr
- src/avram/query_builder.cr
Fixes #370 
Querying with joins can sometimes produce invalid sql. The two cases that this PR handles are:
1. When they potential join is to the table being queried
2. When the potential join has already been joined
These situations are rather easy to get to when users attempt to make composable methods that limit the scope of queries. Say an app has the concept of a `Business` and a `User` and if the user belongs to a business they are considered an `Employee` of that business. If the app allowed users to access the api, it might make sense to limit their API access to businesses they are an employee of. Rather than having to remember how to scope their access correctly every time you have a new query, you could make helper methods like (granted this is convoluted, I'm sure there are …
> Handle duplicate joins

- spec/save_operation_callbacks_spec.cr
- spec/validations_spec.cr
- src/avram/callbacks.cr
- src/avram/save_operation.cr
This PR is the next in the series for https://github.com/luckyframework/avram/pull/369 which covers a few things related to callbacks.
Fixes #480 
* Fixes using `after_save` and `after_commit` with blocks which previously raised errors.
* Added new `skip_before_save`, `skip_after_save`, and `skip_after_commit` methods that allow for skipping named callbacks. Not able to skip block callbacks.
* Breaks calling the `valid?` method to run the `before_save` callbacks. 
For a little more info on that last item, the current implementation allows you to manually call `valid?` which will [run before_save callbacks](https://github.com/luckyframework/avram/blob/master/src/avram/save_operation.cr#L220). Right now it's possible that before_save could be called …
> Better callbacks for SaveOperation

- spec/operations/define_attribute_spec.cr
- spec/operations/nested_save_operation_spec.cr
- spec/operations/operation_callbacks_spec.cr
- spec/operations/operation_needs_spec.cr
- spec/operations/operation_spec.cr
- spec/operations/save_operation_callbacks_spec.cr
- spec/operations/save_operation_spec.cr
- src/avram/callbacks.cr
- src/avram/define_attribute.cr
- src/avram/needy_initializer_and_save_methods.cr
- src/avram/save_operation_template.cr
This PR is the next in the series for https://github.com/luckyframework/avram/pull/369 which doesn't really add anything. This is more of a general cleanup start. I didn't want to get too crazy.
* Remove all the remnants of the old Forms and past Operation stuff that's been gone for a few versions now
* Moved all the operation related specs to its own folder for a bit of organization.
I didn't move the attribute or the validation specs. I was on the fence, but If anyone has a preference I could go either way. 
On a side note, this is just related to Operations, but I'd eventually like to do this for all sections (i.e. models, queries, etc...)
> Operation cleanup

- src/avram/needy_initializer_and_save_methods.cr
Fixes #313 
A part of the https://github.com/luckyframework/avram/pull/369 series. This is just an extra development level catch in case you pass a raw hash in to a SaveOperation create or update. I tested this by adding a spec that does it. 
On a side note, testing compile-time errors is impossible. I wonder if we should create a spec directory with commented out tests that would be designed for just having a way to make sure they work the way we think... 🤔  it would be a little weird and messy, but something to think about.
> Add compile-time error when passing a raw Hash in to SaveOperation.create/update

- src/avram/database.cr
- src/avram/database/column_info.cr
- src/avram/database/database_info.cr
- src/avram/database/table_info.cr
- src/avram/schema_enforcer.cr
Connected #462 
This is part 1 of refactoring `SchemaEnforcer`. This adds `Avram::Database::DatabaseInfo` to every `Avram::Database` which pulls all of the tables and columns from that database for application use and memoizes it. This means that we only run one query for all the database information instead of a query each time we need the information.
It also opens up the query to pull more than just the most basic information. It now has all view table information as well as regular tables so that views can be handled. Future schema enforcers could be added to check data types of columns, as well.
table and column table info:
- https://www.postgresql.org/docs/11/infoschema-tables.html
- https://www.postgresql.org/docs/11/infoschema-columns.html
> Add DatabaseInfo for SchemaEnforcer use

- src/avram/database.cr
Adding Lucky to TechEmpower benchmarks showed us that we were hitting Postgres' connection limit. The pool limit we set for our app was 56 per connection. Starting 10 instances of the app should have only opened up 560 connections, but we started hitting the postgres configuration's 2000 connection limit! Adding in some puts debugging showed that this `Avram::Database#db` method was getting called and going past the memoized value more than we were expecting. The theory is that an instance of the app was handling requests so fast that another request tried to get a database connection before the previous one had fully opened one and set the class variable. The load test was going so fast that it was sending a ton of requests into this situation, thus hitting the connection limit.
By …
> Open database connection in mutex

- src/avram/needy_initializer_and_save_methods.cr
Make it clearer which one is preferred. The hash conversion may be useful in some spots but named args are better in the vast majority of cases because it can catch errors with column names, or value types. The hash on the other hand can have incorrect keys or values
Also adds `record` to the update example
> Clarify which method is preferred + fix update example

- shard.yml
- spec/operations/save_operation_callbacks_spec.cr
- spec/preloading_spec.cr
- src/avram/callbacks.cr
Fixes #483 
This PR does 2 things.
* It removes the `skip_*` macros that I just put in the other day
* It adds in the ability to conditionally run callbacks
You can read through the issue for more info, but a quick TL;DR: You can still skip callbacks, it's just done by override a method yourself instead of a macro doing it for you.
This allows us to now do things like this:
```crystal
abstract class SaveTransaction < Transaction::SaveOperation
before_save :validate_card_number, if: :new_transaction?
def validate_card_number
card_number.value == 42
end
end
class CreateTransaction < SaveTransaction
permit_columns :card_number, :exp_date
private def new_transaction?
true
end
end
class UpdateTransaction < SaveTransaction
permit_columns :exp_date
private def new_transaction?
false
end
end
```
> Adding conditional callbacks

- src/avram/associations/has_many.cr
> Don't preload through association of has_many on count

- spec/preloading_spec.cr
- src/avram/associations/belongs_to.cr
- src/avram/associations/has_many.cr
- src/avram/associations/has_one.cr
- src/avram/base_query_template.cr
- src/avram/primary_key_queryable.cr
- src/avram/query.cr
- src/avram/queryable.cr
- src/avram/save_operation.cr
- src/avram/save_operation_template.cr
I've been doing some experiments and using the "core" of Avram to avoid having to start from scratch. There is quite a bit of code I've had to add that I realized I shouldn't have to. In a bunch of places we were setting things up in a macro when we could move it down into the abstract classes and modules because they (should) take in the generic class it's working with (the `Avram::Model`) and we can expect that to have a lot of helpful class methods. By doing this, we remove a fair bit of code from macros which I consider a win.
> General core cleanup

- spec/query_builder_spec.cr
- src/avram/query_builder.cr
- src/avram/where.cr
Fixes https://github.com/luckyframework/avram/issues/487
With the addition of `OR` to the query builder, where clauses can no longer be uniquely filtered because two clauses are not equal just because they have they same condition, they could be separated by an `OR` and affect the outcome if removed. For example, these two clauses are not the same but the current query builder would turn the first into the second because of the way it checks for uniqueness:
```sql
SELECT *
FROM users
WHERE name = 'Paul'
AND age = 18
OR name = 'Paul'
AND age = 100;
```
```sql
SELECT *
FROM users
WHERE name = 'Paul'
AND age = 18
OR age = 100;
```
This will not affect any queries negatively as truly duplicate conditions are handled as expected by Postgres.
> Remove unique filter of where clauses

- src/avram/migrator/create_table_statement.cr
Fixes https://github.com/luckyframework/avram/issues/501
The error looks like:
```
Error: Unexpected call to `belongs_to` in a migration.
Found in /Users/matthew/workspace/crystal/avram/db/migrations/20201110211223_bad_migration.cr:7:18.
Did you mean to use 'add_belongs_to'?
'add_belongs_to foo : Foo, ...'
```
> Add helpful error when using belongs_to in migration

- src/avram/migrator/alter_table_statement.cr
Improve error reporting for migration where a user accidently includes the type alongside the var name for rename, rename_belongs_to, remove, remove_belongs_to. 
For example:
remove name : String
produces the following error:
Error:
"remove" expected a symbol like ':user', instead got: 'name : String'.
in: "/data/db/migrations/20170127143149_create_users.cr":19:14
Try replacing...
▸ 'name : String' with 'name'
> Improve alter migrations error msg

- spec/support/models/comment.cr
- src/avram/associations/belongs_to.cr
- src/avram/associations/has_many.cr
- src/avram/associations/has_one.cr
- src/avram/base_query_template.cr
- src/avram/model.cr
Breaking out changes from https://github.com/luckyframework/avram/pull/525 to reduce its size.
In all places except belongs_to, we are using the association name instead of trying to infer the table name. It isn't necessary to make this inference though. Anywhere we access the table name from the association, we can use the constant `::TABLE_NAME` or the class method `.table_name`. The belongs to macro is still inferring the table name for now because replacing it with the association name takes it from plural to singular and that leads to all the changes made in the PR this is coming from.
> Update association property to assoc_name instead of table_name

- src/avram/tasks/gen/migration.cr
lucky gen.migrations now returns an error if the migration name already exists.
Fixes issues: https://github.com/luckyframework/avram/issues/521
Error message is:
Migration name must be unique
Migration name: repeat_migration.cr already exists as: 20201112200313_repeat_migration.cr.
Also added tests for the above and for camel case.
> Fix duplicate migration names

- src/avram/callbacks.cr
Also updated the error to include the name of the operation.
Fixes #530
> Catch when before is called with a block in an operation

- spec/operations/operation_errors_spec.cr
- src/avram/operation.cr
- src/avram/operation_errors.cr
- src/avram/save_operation.cr
Fixes #529 
This allows you to set custom errors not related to attributes. When you set an error message, the whole operation is no longer valid.
The main use case is when your operations (or save operations) need some external object, but that object itself may also not be valid.
```crystal
class SaveMessage < Message::SaveOperation
needs user : User
before_save do
if user.is_not_allowed_to_save_message?
add_error(:user_not_welcome, "You don messed up A A ron.")
end
end
end
SaveMessage.create(user: current_user) do |op, _|
op.errors[:user_not_welcome] == ["You don messed up A A ron"]
end
```
> Custom errors and valid property on Operations

- spec/operations/save_operation_spec.cr
- spec/support/models/company.cr
- src/avram/save_operation.cr
Fixes https://github.com/luckyframework/avram/issues/539
Does not filter out unchanged attributes, only nils, on inserting. This allows creating a model with the same value as the default.
> Allow insert giving default value

- spec/spec_helper.cr
- src/avram/database.cr
- src/avram/database/table_info.cr
We were truncating all table names in DatabaseInfo. This included:
- The migrations table
- Non-tables like views
This bug showed itself while running specs in generated Lucky apps because the database is truncated after every test.
We did not see this in Avram because the specs did not load the database migrations which it now does.
The bug started in https://github.com/luckyframework/avram/commit/361a9e84d4b1d3cf35346f6eb361c9388bcaccf0
> Only truncate expected database tables

- db/migrations/20201111220713_create_customers.cr
- spec/associations_spec.cr
- spec/preloading_spec.cr
- spec/query_associations_spec.cr
- spec/queryable_spec.cr
- spec/support/boxes/customer_box.cr
- spec/support/models/customer.cr
- spec/support/models/employee.cr
- spec/support/models/line_item.cr
- spec/support/models/manager.cr
- spec/support/models/post.cr
- spec/support/models/product.cr
- src/avram/associations/belongs_to.cr
- src/avram/associations/has_many.cr
- src/avram/associations/has_one.cr
- src/avram/base_query_template.cr
- src/avram/model.cr
Fixes #523 
Fixes #473
Fixes: #496
Related (but does not fix): #196
Had to bring in the changes in #494 and #499 in order to get it working.
- Updates "has many through"'s to take in an array in the `through` field.
- Belongs to associations now have singular "where_xxx" queries
```crystal
class Manager < BaseModel
table do
has_many employees : Employee
has_many customers : Customer, through: :employees
end
end
```
```crystal
class Manager < BaseModel
table do
has_many employees : Employee
has_many customers : Customer, through: [:employees, :customers]
end
end
```
The array is the association route to get to the customers. So Manager will need to have an association with the name of `employees` and Employee is expected to have an association called `customers` that returns Customer. …
> Model association updates

- spec/operations/save_operation_callbacks_spec.cr
- src/avram/callbacks.cr
- src/avram/save_operation.cr
Fixes #432 
Also see comment: https://github.com/luckyframework/avram/pull/481#issuecomment-713881686
This is a new callback added for SaveOperation that will run after commits, but this also runs even if no changes are happening to the record. As where `after_commit` only runs if an actual DB commit happens, `after_completed` will run even when there's no changes to be made.
Naming is hard, so I'm down for a different name. I also thought about calling it `after_finalized` or `after_succesful_run`.
Another option I toyed with was doing `after_validated`; however, I felt that a name like that would imply that it would run after the `valid?` calls... This would allow us to call in both spots, but the original issue for #432 wanted to run things after stuff was saved, and that would not be …
> Adding in a new after_completed callback

- src/avram/base_query_template.cr
- src/avram/model.cr
- src/avram/primary_key_queryable.cr
- src/avram/save_operation_template.cr
Related to: https://github.com/luckyframework/avram/issues/6
Related to: https://github.com/luckyframework/avram/issues/453
Another step on the way on breaking the requirements on having primary keys. If you did not provide a primary key in the model, it immediately failed when trying to run the `setup` macro. Now, anywhere that uses the primary key pulls it through the `Crystal::Macros::TypeNode#constant` which returns `NilLiteral` if the constant is not found.
> Remove primary key name and type from Model setup macro

- db/migrations/20180628193054_create_product.cr
- spec/schema_enforcer/ensure_uuid_primary_key_has_default_spec.cr
- src/avram/database/column_info.cr
- src/avram/database/database_info.cr
- src/avram/schema_enforcer/ensure_uuid_primary_key_has_default.cr
Related to https://github.com/luckyframework/avram/issues/393
If we ever wanted to support generating UUID primary keys from the database, this validation will aid in catching tables that need to be updated to set a default value. I did **not** add it to the list of validations that run by default.
> UUID schema enforcer

- spec/preloading/preloading_belongs_to_spec.cr
- src/avram/associations/belongs_to.cr
Part 1 of https://github.com/luckyframework/avram/issues/531
Provides a way to preload associations onto existing records. This is especially useful when you have helper methods for your actions to load certain objects from the database but don't have associations preloaded for an association needed in a particular action. You could either update that helper method to preload the association you need, but that could be overkill for your other actions. You could also make a separate query for the association records but they won't be connected to the other record so you have to pass around both where they are needed.
```crystal
user.organization # LazyLoadError
user = UserQuery.preload_organization(user)
user.organization # Success!
```
> Add belongs_to preload methods for existing records

- spec/preloading/preloading_has_one_spec.cr
- src/avram/associations/has_one.cr
Part 2 of https://github.com/luckyframework/avram/issues/531
> Can preload has_one associations with existing records

- spec/schema_enforcer/ensure_matching_columns_spec.cr
- src/avram/model.cr
- src/avram/schema_enforcer.cr
- src/avram/schema_enforcer/ensure_existing_table.cr
- src/avram/schema_enforcer/ensure_matching_columns.cr
- src/avram/schema_enforcer/ensure_uuid_primary_key_has_default.cr
- src/avram/schema_enforcer/validation.cr
Related to https://github.com/luckyframework/avram/issues/453
Related to https://github.com/luckyframework/avram/pull/555
In order for views to work with SchemaEnforcer, `EnsureMatchingColumns` has to have a configuration to not check required vs. nilable on columns since all columns are nilable in views. This update also changes how we set up validations for SchemaEnforcer so that tables _could_ have different validations than views and there's a way to add/remove/customize validations
> Schema enforcer update

- db/migrations/20201202225520_create_admin_users_view.cr
- db/migrations/20201202231134_create_nickname_infos_view.cr
- spec/support/models/admin_user.cr
- spec/support/models/nickname_info.cr
- spec/view_spec.cr
- src/avram/model.cr
Fixes https://github.com/luckyframework/avram/issues/453
To declare a view, instead of using the `table` macro, there is now a `view` macro. There are a few differences between the two:
- There are no default columns. If your view has a primary key or timestamps, they must be defined explicitly
- No `Model::SaveOperation` is defined
- If the view does not have a primary key, some methods don't work or will be missing
- `Avram::Model#reload` raises a compilation error if invoked without a primary key
- `Model::BaseQuery` no longer includes `Avram::PrimaryKeyQueryable` which has methods like `#find` that require a primary key
No functionality around materialized views is included with this change.
> Add support for database views

- spec/model_spec.cr
- src/avram/model.cr
- src/avram/primary_key_methods.cr
Fixes https://github.com/luckyframework/avram/issues/558
Adds an implementation when primary key is defined, otherwise raises a compilation error when used.
> Add back Avram::Model#to_param

- src/avram/associations/belongs_to.cr
- src/avram/associations/has_one.cr
Related to https://github.com/luckyframework/avram/issues/531
There were overloads added of preloading functions in https://github.com/luckyframework/avram/pull/561 that were not defined for belongs_to or has_one associations.
> Add missing overloads for belongs to and has one preloading with existing records

- spec/preloading/preloading_has_many_spec.cr
- spec/preloading/preloading_has_many_through_spec.cr
- src/avram/associations/has_many.cr
Fixes https://github.com/luckyframework/avram/issues/531
This is one of the last updates to support preloading associations with existing records. It adds support for has many and has many through associations.
There were some overloaded methods added that are not defined for belongs to or has one associations to support has many through's. I will make another PR adding those so that all associations have every method overload.
> Can preload has many associations with an existing record

- src/avram/model.cr
- src/avram/primary_key_methods.cr
Related to https://github.com/luckyframework/avram/issues/453
The delete method only works when there is a primary key defined. This updates the implementation to raise a compile-time error if used when no primary key is defined.
Also a small modification to the other compile time error messages.
> Define Avram::Model#delete only when primary key defined

- spec/queryable_spec.cr
- src/avram/queryable.cr
Fixes #547 
When we merged in https://github.com/luckyframework/avram/pull/411 this broke the ability to easily set defaults on your query objects.
Before that PR you could do this:
```crystal
class SomeQuery < User::BaseQuery
def initialize
age.gte(21)
end
end
SomeQuery.new
```
After that PR, you would have to manually set the query object to get the same effect
```crystal
class SomeQuery < User::BaseQuery
def initialize
self.query = age.gte(21).query
end
end
```
With this PR, you can still set the query object manually if you want, but this adds in a new `defaults` method to make it a little more clear on what your intension is. Note that this method is set to `private` because you shouldn't call this from outside of the query class. 
```crystal
class SomeQuery < User::BaseQuery
def …
```
> Adding helper method for defaults.

- spec/type_extensions/enum_spec.cr
- src/avram/charms/enum_extensions.cr
This implements `==` and `===` methods on avram_enum generated structures, and also implements explicit constant accessors to decrease the difference between Enum and avram_enum.
> Updates to Avram Enums : ==, ===, enum constants

- spec/associations_spec.cr
- src/avram/model.cr
Fixes #571
Turns out this affected all associations. We never caught this because the tests only ever setup a single record. Since we were calling `type`, the associations never matched because `Tag` would never equal `:belongs_to`.
> fixing bug with associations

- shard.yml
- src/avram/version.cr
This release contains an urgent fix to associations, and a fix to enums that didn't allow you to do comparisons on them.
> Release 0.18.1

- spec/migrator/migration_spec.cr
- spec/spec_helper.cr
- spec/tasks/db_create_spec.cr
- spec/tasks/db_schema_dump_spec.cr
- spec/tasks/db_schema_restore_spec.cr
- spec/tasks/db_verify_connection_spec.cr
- src/avram/errors.cr
- src/avram/migrator/migration.cr
- src/avram/migrator/migrator.cr
- src/avram/migrator/runner.cr
- src/avram/tasks/db/base_task.cr
- src/avram/tasks/db/create.cr
- src/avram/tasks/db/drop.cr
- src/avram/tasks/db/migrate.cr
- src/avram/tasks/db/migrate_one.cr
- src/avram/tasks/db/migrations_status.cr
- src/avram/tasks/db/redo.cr
- src/avram/tasks/db/reset.cr
- src/avram/tasks/db/rollback.cr
- src/avram/tasks/db/rollback_all.cr
- src/avram/tasks/db/rollback_to.cr
- src/avram/tasks/db/schema_dump.cr
- src/avram/tasks/db/schema_restore.cr
- src/avram/tasks/db/setup.cr
- src/avram/tasks/db/verify_connection.cr
- tasks.cr
Fixes https://github.com/luckyframework/avram/issues/422
While the errors might look "uglier", they will now definitely contain the error message and the stacktrace.
Instead of dropping exceptions for new messages with a new stacktrace, this raises a new error with the original error as the cause so that we can add info without forgetting context. The only problem was that Crystal does not print the "cause" of unhandled exceptions ([source](https://github.com/crystal-lang/crystal/blob/33670931a7ac56fa3e7b737957a9c6413605eb83/src/crystal/system/print_error.cr#L15-L28)). To overcome this, I updated `Avram::Migrator` to print the error so that we can get the cause and then to exit so that it's still recognized as a failure.
> Don't obscure errors during migrations

- db/migrations/20180625202051_create_line_item.cr
- db/migrations/20180628193054_create_product.cr
- spec/migrator/create_table_statement_spec.cr
- spec/schema_enforcer/ensure_uuid_primary_key_has_default_spec.cr
- src/avram/migrator/columns/primary_keys/uuid_primary_key.cr
Fixes https://github.com/luckyframework/avram/issues/122
When a user creates a migration that uses a UUID primary key, the migration will automatically set the default value to be `gen_random_uuid()` which comes from the `pgcrypto` extension. If they do not have that extension enabled, the migration will fail saying that `gen_random_uuid()` is an unknown function. They will need to add `enable_extension "pgcrypto"` in their migration before creating the table to get it working.
This does not remove or change how Avram currently sets the id value itself before inserting the record into the database https://github.com/luckyframework/avram/blob/1e6f4edd4d49c518c858ee9ecc277a3b963051eb/src/avram/save_operation_template.cr#L15-L22
We will definitely need to consider how we want to make that …
> Generate UUID primary keys in the database

- spec/validations_spec.cr
- src/avram/validations.cr
Fixes #570 
I have seen `validate_size_of` mistakenly used to validate a numeric value since the name doesn't give any indication that the implementation expects strings. As the connected issue points out, even the documentation seems confused.
This change updates the type signature to allow only attributes that contains strings. While the type signature says it only takes in `Avram::Attribute(String?)`, I found it also handles `Avram::Attribute(String)`. I didn't expect it to be that smart 😄
> Restrict validate_size_of to string attributes

- spec/validations_spec.cr
- src/avram/validations.cr
Completes #537 
```crystal
validate_numeric age, greater_than: 18, less_than: 65
```
Any type of number can be used for the attribute or the conditions since they can all be compared.
> Add validation for numbers

- spec/lazy_loading_spec.cr
- src/avram/associations/has_one.cr
The code was still depending on the query being mutated instead of immutable so it was always loading the first association in the database. This only affected code that was using lazy loading (by enabling it or using the bang methods).
> Load correct has_one association with lazy loading

- spec/attribute_spec.cr
- spec/operations/define_attribute_spec.cr
- spec/validations_spec.cr
- src/avram/attribute.cr
- src/avram/define_attribute.cr
- src/avram/delete_operation.cr
- src/avram/save_operation.cr
- src/avram/validations.cr
I'm starting to look into https://github.com/luckyframework/avram/issues/408 but noticed that the generics for `Avram::Attribute` were a bit weird. We document that values for attributes are always nilable but that wasn't necessarily true. It's always nilable because where ever we were "new-ing" up an attribute we were doing so in a macro and adding in a `?` to whatever type was supplied but the attribute's type could have been anything (including not nilable). We can avoid doing that in the macros by making the attribute's value nilable within the class. So `Avram::Attribute(String?)` becomes `Avram::Attribute(String)` but `Avram::Attribute(String)#value` is still `String?`
This would be a breaking change for anyone referencing the type. For instance, some validations had to be updated …
> Update how generics work for Avram::Attribute

- spec/support/custom_email.cr
- spec/type_extensions/array_spec.cr
- spec/type_extensions/int32_spec.cr
- spec/type_extensions/time_spec.cr
- spec/type_extensions/uuid_spec.cr
- src/avram/between_criteria.cr
- src/avram/charms/array_extensions.cr
- src/avram/criteria.cr
- src/avram/define_attribute.cr
- src/avram/delete_operation.cr
- src/avram/model.cr
- src/avram/save_operation.cr
- src/avram/uploadable.cr
Related to #408 
This brings several advantages
- We can potentially remove the Lucky namespace from Avram code
- Custom types only have to implement the method instead of the namespace
- There were bugs with generic classes where `Array(String)` was made into `Array(String)::Lucky` which doesn't work but the method does
This is a breaking change as anyone using custom types will need to add this adapter method if they didn't already.
This does not fix the related issue because the `Array.adapter` method delegates to the generic class which means there's no support for turning, for example, a string param into an array
https://github.com/luckyframework/avram/blob/03d1a7bcc981a75b103c2f54b81a430096ea0c84/src/avram/charms/array_extensions.cr#L2-L6
> Use .adapter instead of using Lucky namespace for parsing

- src/avram/tasks/db/console.cr
Fixes #516
This task just calls `psql` passing in your configured DB URL. I have no idea how to test this 😂
> Added simple task to enter db console

- spec/support/custom_email.cr
- src/avram/base_query_template.cr
- src/avram/charms/bool_extensions.cr
- src/avram/charms/enum_extensions.cr
- src/avram/charms/float64_extensions.cr
- src/avram/charms/int16_extensions.cr
- src/avram/charms/int32_extensions.cr
- src/avram/charms/int64_extensions.cr
- src/avram/charms/json_extensions.cr
- src/avram/charms/string_extensions.cr
- src/avram/charms/time_extensions.cr
- src/avram/charms/uuid_extensions.cr
No connected issue
After https://github.com/luckyframework/avram/pull/587, there was a still one place with a hard-coded reference to the type extension namespaces https://github.com/luckyframework/avram/blob/5f51bebce324a2b3a0aa3b0457b3799d567a3150/src/avram/base_query_template.cr#L14-L19
This adds a `criteria` method that takes in the query and the column name and returns an instance of an `Avram::Criteria` for the given type.
One of the other benefits it gives us is that we don't need special handling for generic types since we are calling methods on the class instead of using it to access a namespace.
This would be a breaking change since the `criteria` method is completely new and custom types would need to implement it.
The rules for adding custom types would be:
- The type must …
> Add a criteria method to the type adapter

- src/avram/attribute.cr
- src/avram/define_attribute.cr
Related to https://github.com/luckyframework/avram/issues/408
My goal is to eventually get to a place where any type of conversion from a thing to an attribute value can be handled and easily added to by users, libraries, and future maintainers of Avram. The way the code was, operations were hard-coded to extract and transform values into attributes with Lucky in mind. Hopefully you can see where these changes are headed towards. Method overloads could be added to support different types to convert the extraction to (like arrays!) or even what we are extracting from (maybe someone wants to use Avram in Amber someday and needs to pull attributes using their params API). Here's what I think the benefits of this change are:
- Have clear ways to statically type the object we're pulling …
> Move param extraction for operations into the attributes

- spec/type_extensions/time_spec.cr
- src/avram/charms/time_extensions.cr
This PR intends to close #602.
You can read more about DateTime Local inputs at this link:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
From what I can gather, browsers basically use [RFC 3339](https://tools.ietf.org/html/rfc3339) without the timezone. Because of this, our `Time::Format::RFC_3339` parser wasn't actually extracting the time element from a `datetime-local` input type in Lucky.
- [TimeExtensions#parse] Add a custom `Time::Format` that will parse these `datetime-local` inputs correctly, though it _will_ always use `Time::Location.local` for the timezone.
- [Specs] Moved the hardcoded strings to use time formatting where possible so that we can test more date/time ranges and check specific time values more easily. 
- [Specs] Add some checks on …
> Support datetime-local time parsing

- spec/type_extensions/time_spec.cr
- src/avram/charms/time_extensions.cr
Previously, we were using `Time.local` and `Time::Location.local`. For reasons we have been unable to discover, the specs would fail for anyone who didn't have their crystal time zone set to UTC.
Forcing this parser and spec to use UTC time is expected to get the test suite green for every scenario.
> Move new HTTP form datetime-local parser to force UTC

- db/migrations/20180612221318_create_businesses.cr
- spec/case_insensitive_column_spec.cr
- spec/support/boxes/business_box.cr
- spec/support/boxes/email_address_box.cr
- spec/support/models/business.cr
- spec/support/models/email_address.cr
- src/avram/migrator/columns/string_column.cr
Fixes #550 
In a migration you'd pass the the `case_sensitive: false` flag to a string column to make its type `citext`. The [citext extension](https://www.postgresql.org/docs/current/citext.html) must be enabled.
```crystal
enable_extension "citext"
create table_for(User) do
add name : String
add email : String, case_sensitive: false
end
```
This would create the `users` table with a case sensitive `name` column and a case insensitive `email` column.
> Add support for case insensitive text columns (citext)

- spec/operations/save_operation_callbacks_spec.cr
- src/avram/callbacks.cr
- src/avram/save_operation.cr
Closes #604
This PR ensures all nested operations called in `after_save` run, at all times, and in a transaction. It is, therefore, automatically rolled back if something goes wrong. Other potential benefits are discussed in the linked issue.
With this, we no longer need #600 for completing #596.
> Run after_save and after_commit even if no changes were made

- spec/migrator/create_table_statement_spec.cr
- src/avram/migrator/create_table_statement.cr
This PR is about the migration part of the composite primary key implementation.
It adds `composite_primary_key` to the create table migrator.
It works like this
```crystal
def migrate
create table_for(UserPost) do
add_belongs_to user : User, on_delete: :cascade
add_belongs_to post : Post, on_delete: :cascade
primary_key :user_id, :post_id
end
end
```
There is still some work to do with add_belongs_to if it's a composite PK but for that it needs some work on the model part.
Issue #129
> Composite primary key migration

- spec/operations/nested_save_operation_spec.cr
- spec/operations/save_operation_spec.cr
- spec/support/factories/tax_id_factory.cr
- src/avram/nested_save_operation.cr
- src/avram/save_operation.cr
Resolves https://github.com/luckyframework/avram/issues/7
This PR seeks to support updating for `.has_one`s. The previous implementation worked for creates, not for updates. So if you called `SomeOperation.update` for an operation that called `.has_one`, you would get an error.
> Handle updates for nested `.has_one` save operations

- src/avram/charms/float64_extensions.cr
- src/avram/model.cr
I didn't really dig into the history of why it was written the way it was, but the `ColumnType` alias for `Float64` was specifically made for that and was unused.
> Remove special handling of Float64 columns

- spec/type_extensions/enum_spec.cr
- src/avram/charms/enum_extensions.cr
Handles cases where an enum value is passed around as a string. The following is possible in Lucky after this change:
```crystal
class Thing < BaseModel
avram_enum Type do
Image
end
table do
column type : Thing::Type
end
end
class SaveThing < Thing::SaveOperation
permit_columns type
end
class Things::NewPage < AuthLayout
needs operation : SaveThing
def content
mount Shared::Field, attribute: op.type, label_text: "Type" do |input_html|
input_html.select_input append_class: "select-input" do
options_for_select op.type, [{"Image", Thing::Type.new(:image)}]
end
end
end
end
```
There's no type conversions to or from strings or integers in this sample code. A string is passed around (the enum value name), and parsed by avram prior to saving.
> Enum string parsing

- db/migrations/20210217224833_add_latitude_and_longitude_to_businesses.cr
- spec/operations/nested_save_operation_spec.cr
- spec/queryable_spec.cr
- spec/support/factories/business_factory.cr
- spec/support/models/business.cr
- spec/type_extensions/float64_spec.cr
- src/avram/charms/float64_extensions.cr
This is a solution for the issue: https://github.com/luckyframework/avram/issues/636
> Add Float64 to ColumnType

- src/avram/migrator/migration.cr
- src/avram/migrator/runner.cr
Cockrochdb uses a bigserial and this breaks with using the migrator.  This is compatible with both postgresql and cockroachdb.
> make migration id bigserial

- src/avram/database.cr
Fixes #416
This allows for code to use transactions like:
```crystal
AppDatabase.transaction do
StepOneOperation.run!
StepTwoOperation.run!
end
```
This would only have worked previously if `StepTwoOperation.run!` returned a boolean. Otherwise `true` would have to be added as the last line because we required the block to return a Bool.
I believe the original type restriction was put in place to match crystal-db's but it was not intention https://github.com/crystal-lang/crystal-db/issues/145
> Remove bool return type restriction on Avram::Database#transaction

- spec/queryable_spec.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
- src/avram/where.cr
Fixes #488
When it comes to more complex queries, you may need to specify precedence for your conditions. This is done by wrapping your condition in parenthesis.
This PR adds a new `where` overload for your query objects that takes a block, and will wrap whatever query is defined inside the block.
```crystal
UserQuery.new
.name("Bill")
.or { |q|
q.where(&.age(19).nickname("Duke"))
}
```
```sql
-- Gives us this SQL
SELECT *
FROM users
WHERE name = 'Bill' OR ( age = 19 AND nickname = 'Duke' )
```
This opens Avram up to a lot more complex (but type-safe) queries.
> New method to add parenthesis to queries

- spec/migrator/drop_foreign_key_statement_spec.cr
- src/avram/migrator/drop_foreign_key_statement.cr
- src/avram/migrator/statement_helpers.cr
In order to complete #622, we have to drop the constraint first, then recreate it with the new `on_delete` statement.
This PR adds in the ability to drop a foreign key constraint which would allow you to change your `belongs_to` if you needed.
```crystal
def migrate
create table_for(Post) do
add_belongs_to user : User, on_delete: :nullify
end
end
def migrate
drop_foreign_key :posts, :users
create_foreign_key :posts, :users, on_delete: :cascade
end
```
This is more of an escape hatch without you having to write all of the SQL by hand. The next step would be a separate PR that implements a `change_belongs_to` type macro.
> Add new method for droping a foreign key constraint in migrations.

- spec/migrator/table_for_spec.cr
- spec/model_spec.cr
- src/avram.cr
- src/avram/base_query_template.cr
- src/avram/errors.cr
- src/avram/insert.cr
- src/avram/join.cr
- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/build_reference_fragment.cr
- src/avram/migrator/change_null_statement.cr
- src/avram/migrator/columns/base.cr
- src/avram/migrator/create_foreign_key_statement.cr
- src/avram/migrator/create_index_statement.cr
- src/avram/migrator/create_table_statement.cr
- src/avram/migrator/create_trigger_statement.cr
- src/avram/migrator/drop_foreign_key_statement.cr
- src/avram/migrator/drop_index_statement.cr
- src/avram/migrator/drop_table_statement.cr
- src/avram/migrator/drop_trigger_statement.cr
- src/avram/migrator/statement_helpers.cr
- src/avram/model.cr
- src/avram/query_builder.cr
- src/avram/table_for.cr
- src/run_macros/infer_table_name.cr
I had heard that using `run` in macros slowed down compilation times. Turns out, it's true!
I ran benchmarks on master and this branch (`hyperfine --warmup 3 'crystal build --release spec/model_spec.cr'`)
master: 5.016 seconds (average)
with these changes: 4.156 seconds (average)
**That's a 17% improvement in release compile time!**
Our only use for `run` was to infer the table name in migrations and in the models. We turned the model name into a symbol that was the table name. We only ever needed this info at runtime so it made sense to bring the code that was in the file being `run`. The only problem is that we can't return a symbol anymore because the table name isn't determined until runtime and it's not possible to construct symbols at runtime. I added a `TableName` alias that is …
> Allow table name to be Symbol or String, remove run from macros

- .github/workflows/ci.yml
We currently only officially test Avram against Postgres 10, which seems less than ideal since the current version is actually 13.
This tests against 10, 11, 12, and 13.
It also adds an experimental test against the Crystal nightly build.
> Add Postgres versions and experimental builds to CI test matrix

- spec/migrator/alter_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
This covers a very edge case when performing migrations that imply adding a not null boolean column filling previous records with the false value.
In practice when performing this kind of modification
```
alter table_for(SomeTable) do
add a_column : Boolean, fill_existing_with: false
```
the migration fails as the fill_existing_with is not considered.
The patch fixes this particular case.
Note 1:
There is currently a way to bypass this by switching the former code to:
```
alter table_for(SomeTable) do
add a_column : Boolean, fill_existing_with: "false"
```
(add double quotes)
Note 2:
the resulting statement is now:
```
UPDATE users SET admin = 'false';
```
Is it correct? I didn't touch the logic in the BoolColumn, but I would assume that in theory it should be without single quotes. …
> Fix edge cases in migrator when using fill_existing_with with a boolean value

- spec/database_spec.cr
- src/avram/connection.cr
- src/avram/database.cr
This allows us to listen for `pg_notify()` calls for any number of channels. 
```sql
SELECT pg_notify('workers', json_build_object('id', 1, 'name', 'test')::text)
```
```crystal
AppDatabase.listen("workers") do |notify|
data = JSON.parse(notify.payload)
puts data["id"] #=> 1
puts data["name"] #=> "test"
end
```
> Adding ability to listen for notifications from postgres

- src/avram/uploadable.cr
In order to get https://github.com/luckyframework/lucky/pull/1519 to work, these changes are needed.
I'm not sure how to test this since the actual error I'm solving is a compile-time error happening in Lucky. Here's a small example of what's going on:
https://play.crystal-lang.org/#/r/bana
```crystal
class SuccessfulCast(T)
def initialize(@value : T)
end
end
module Uploadable
end
class Upload
include Uploadable
end
def parse(values : Array(Uploadable))
SuccessfulCast(Array(Uploadable)).new(values)
end
values = [Upload.new]
parse(values)
```
> Error: instance variable '@value' of SuccessfulCast(Array(Uploadable)) must be Array(Uploadable), not Array(Upload)
In this case, the compiler isn't able to determine that `Avram::Uploadable` and `Lucky::UploadedFile` are the same. To get around …
> Fixes for Array(Uploadable)

- spec/migrator/alter_table_statement_spec.cr
- spec/migrator/create_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/create_table_statement.cr
Fixes #684 
`add_belongs_to namespaced_assoc : Namespaced::Assoc, on_delete: :cascade`
Before: `namespaced::assocs`
After: `namespaced_assocs`
> Support belongs to with namespaced classes

- spec/queryable_spec.cr
- src/avram/queryable.cr
Fixes #686
This new way now allows for counting against more complex queries which include using `distinct_on`. The main reason for this is using pagination when you have these complex queries.
Before this PR, you couldn't do this:
```crystal
get "/messages" do
pages, messages = paginate(MessageQuery.new.distinct_on(&.status))
html IndexPage, messages: messages, pages: pages
end
```
This would throw an error that `status` needs to be in a "GROUP BY" or used in an aggregate function. But of course, if you added `status` to a group, it would also want `id`, and you'd still have to change the count from `COUNT(*)` to `COUNT(status)` or something else... 
Also as @wyhaines pointed out in [686](https://github.com/luckyframework/avram/issues/686#issuecomment-862664764), there's several cases …
> Changing how the select_count method counts returned rows.

- spec/type_extensions/time_spec.cr
- src/avram/charms/time_extensions.cr
Closes https://github.com/luckyframework/lucky/issues/1530
I originally fixed this here: https://github.com/luckyframework/avram/pull/603
At least, LuckyCasts DateTime inputs were working at some point with this PR. However, since then, it appears as though that's stopped working:
https://github.com/luckyframework/lucky/issues/1530
I attempted to refactor this test file to make it a bit cleaner and easier to extend with other tests in the future. I'm not sure if I should put the struct/enum in another `support` file or something, but it made sense to me to keep it local to the test since this is the only place it was needed.
I've tested this branch with LuckyCasts, and DateTimes are saving correctly with it in place.
> Fix DateTime Form Input Parsing

- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/create_table_statement.cr
Fixes #689 
Imagine accidentally doing `add admin : Boolean` where `Boolean` should have actually been `Bool` but you forgot.
Before this change the error you got from that would look like:
With this change, it now looks like:
> Resolve type before using it in migrations

- spec/validations_spec.cr
- src/avram/database_validations.cr
Fixes #368 
Fixes https://github.com/luckyframework/lucky/issues/1482
Allows for passing a query to the uniqueness validation without specifically passing in a criteria.
If all you wanted to do was limit the uniqueness validation by a different column, before you had to do:
```crystal
validate_uniqueness_of email, query: UserQuery.new.tenant(1).email
```
Now you can do:
```crystal
validate_uniqueness_of email, query: UserQuery.new.tenant(1)
```
It's a small change but it cuts down on confusion and allows users to be clear on what they are actually trying to do.
Other changes were made (I can extract them if necessary)
1. The docs were wrong and have been fixed (on the wrong overloads)
2. The criteria overload was missing the limit to ignore the current record if it was an update
3. …
> Add uniqueness validation providing query

- spec/queryable_spec.cr
- src/avram/database.cr
- src/avram/database_validations.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
Fixes #680 
Provides two simple methods to check if there are any records in the database matching the specified conditions. Within avram's codebase, it simplifies the uniqueness checks.
Usage looks like:
```crystal
UserQuery.any?
UserQuery.new.name("Sally").any?
```
> Add any? and none? as query methods

- spec/support/factories/issue_factory.cr
- spec/support/models/issue.cr
- spec/type_extensions/enum_spec.cr
- src/avram/charms/enum_extensions.cr
- src/avram/criteria.cr
- src/avram/type.cr
Fixes https://github.com/luckyframework/avram/issues/590
Fixes https://github.com/luckyframework/avram/issues/610
Related to https://github.com/luckyframework/avram/issues/697
I was able to drop the need for having the `avram_enum` macro and allow using regular enums. I'm somewhat worried that by dropping the macro that creates a struct, we will be losing functionality but I can't find anything.
It was added in https://github.com/luckyframework/avram/pull/339 but I don't see any specifics as to why they did what they did.
I did find one problem with `Avram::Criteria` and enums that affects `avram_enums` as well where calling `select_max` would return an `Int32` instead of the enum value.
I think the end goal is to allow storage of enums in the database as something other than `Int32` but …
> Use simple enums for Avram columns

- spec/operations/delete_operation_callbacks_spec.cr
- spec/operations/delete_operation_spec.cr
- spec/operations/operation_needs_spec.cr
- src/avram/delete_operation.cr
- src/avram/errors.cr
- src/avram/needy_initializer_and_delete_methods.cr
Fixes https://github.com/luckyframework/avram/issues/694
> Rename DeleteOperation#destroy to #delete

- src/avram/model.cr
Fixes https://github.com/luckyframework/avram/issues/699
> Require at least one column defined on models

- spec/query_builder_spec.cr
- src/avram/query_builder.cr
Fixes #712
Clone the queries, so the subsequent calls to #statement and #statement_for_update returns the same result.
https://github.com/luckyframework/avram/blob/e638ffb8eb5e8088449dfa63cb61a0739212f38d/src/avram/queryable.cr#L227-L230
> Don't mutate the query builder when calling the statement methods

- src/avram/tasks/db/migrations_status.cr
- src/avram/tasks/db/rollback_to.cr
Correct command is `db.migrations.status` ("migration**s**" <-- plural)
Originates from commit f3d6328d25732aaa6359b8e9f7a670df2aef5b41.
> Fix wrong command in help messages

- src/avram/save_operation.cr
Fixes #719
Hi @jwoertink, how does this look?
Let me know if this needs any changes.
Thanks
> fix: add the operation name to the unpermittable column error

- spec/operations/delete_operation_spec.cr
- spec/operations/operation_errors_spec.cr
- spec/operations/save_operation_spec.cr
- src/avram/delete_operation.cr
- src/avram/mark_as_failed.cr
- src/avram/save_operation.cr
Fixes #758
This helps to avoid name collisions if you happen to create a model named `Status`
> Rename Status enums in operations.

- src/avram/migrator/migration.cr
- src/avram/migrator/runner.cr
Fixes #768
I'm trying to fix this CI failure in LuckyCLI https://github.com/luckyframework/lucky_cli/runs/4372596405?check_suite_focus=true#step:9:511 but I'm unable to recreate the same issue locally. Hopefully using `sort_by`, and forcing the `Int64` type should allow the compiler to better know what's going on 🤷‍♂️
> Fixing migration sorting

- spec/queryable_spec.cr
- src/avram/criteria.cr
- src/avram/order_by_clause.cr
- src/avram/order_by_clause/order_by.cr
- src/avram/order_by_clause/order_by_random.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
Here's a proposal for the `random_order` implementation (https://github.com/luckyframework/avram/issues/755).
Initially, I tried to add a `:random` option to `Avram::OrderBy` but a few things were bad about that approach:
- too many if statements to switch between _order by random_ and _order by column_ clauses
- unnecessary attributes for the random option
- unused `column` argument in the initializer, requiring the `column` attribute to be nilable
- clunky internal API (e.g. `Avram::OrderBy.new(nil, :random)`)
That's why I decided to create an abstract class called `Avram::OrderByClause` and split out the two different order methods into two subclasses called `Avram::OrderBy` and `Avram::OrderByRandom`. The `Avram::OrderBy` class could have been renamed to `Avram::OrderByColumn` for …
> Add random_order method to query objects

- src/avram/primary_key_queryable.cr
`#first?` already does the limit so this is duplicated
https://github.com/luckyframework/avram/blob/e377697bb562963a1ab2d319c206f2c296e208d5/src/avram/queryable.cr#L196-L201
> Remove redundant limit from #find

- db/migrations/20220111192510_create_articles.cr
- shard.yml
- spec/avram/slugify_spec.cr
- spec/support/factories/article_factory.cr
- spec/support/models/article.cr
- src/avram.cr
- src/avram/slugify.cr
Closes https://github.com/luckyframework/avram_slugify/issues/13
This pulls the entire `AvramSlugify` shard directly in to Avram as `Avram::Slugify`. No usage or features have changed aside from the name scope. The main considerations for bringing this over are
* 1 less shard to maintain. Each Avram release required making sure AvramSlugify was also in-sync
* It's a super small shard with only 1 file (~ 45 LOC)
* New features become easier to implement with Avram being readily available
The specs weren't copy/paste since the shard was using a `User` model that wasn't setup the same. I decided to just make a separate model for testing that.
The only other main thing to consider was whether or not to make this an optional require. On the one hand, we could add it as its own module where …
> Integrating AvramSlugify

- spec/avram/transaction_spec.cr
- src/avram/database.cr
Fixes #799
I think the original check was the opposite (if connection has no open transactions) and I forgot to negate when I switched to this method. The specs didn't catch it because almost all specs run within a transaction so they just so happened to always fall into this block 🤦.
> Release connections correctly

- spec/avram/queryable_spec.cr
- src/avram/database.cr
Fixes #799
In https://github.com/luckyframework/avram/pull/800 we already fixed one place where we weren't releasing connections correctly. We found another place where queries were not releasing connections since they don't use transactions. Instead of add the connection release code in two places, I updated `current_connection` to be `with_connection` that takes a block. When the block finishes (error or not) it will always attempt to release the connection back to the pool. If there is an open transaction, it won't do it.
> Update how db connections are retrieved and released

- shard.yml
https://github.com/will/crystal-pg/compare/v0.24.0...v0.26.0
https://github.com/crystal-lang/crystal-db/compare/v0.10.1...v0.11.0
This adds the upstream changes from crystal-pg v0.11
This also allows us to remove the monkey patches required for null array
elements in avram, added/utilized by the bulk upsert functionality #789
> Update to crystal-pg v0.26.x

- spec/avram/json_column_spec.cr
- src/avram/charms/json_extensions.cr
Connected to https://github.com/luckyframework/lucky/pull/1661
When we call `params.nested(:user)` we get back a `Hash(String, String)`. The String value is a stringified version of the json object which the current implementation would not parse correctly. This new overload attempts to parse the raw string value before calling `.to_json` on it.
This does change behavior:
```crystal
JSON::Any.adapter.parse("true") #=> "true" : JSON::Any (before)
JSON::Any.adapter.parse("true") #=> true : JSON::Any (after)
JSON::Any.adapter.parse("1") #=> "1" : JSON::Any (before)
JSON::Any.adapter.parse("1") #=> 1 : JSON::Any (after)
JSON::Any.adapter.parse("{\"foo\":\"bar\"}") #=> "{\"foo\":\"bar\"}" : JSON::Any (before)
JSON::Any.adapter.parse("{\"foo\":\"bar\"}") #=> {"foo" => "bar"} : JSON::Any
```
I …
> Attempt parsing raw string before calling to_json

- spec/avram/preloading/preloading_belongs_to_spec.cr
- spec/avram/preloading/preloading_has_one_spec.cr
- src/avram/associations.cr
- src/avram/associations/belongs_to.cr
- src/avram/associations/has_one.cr
- src/avram/errors.cr
Related #672 
If a model defines a required belongs to association and the record isn't retrieved in a preload, this raises an appropriate error. Also added for required has one associations.
Applying this to the related issue, in the scenario where you have soft deletes, the solution now becomes making what was a required association optional since it might not always be loaded. This doesn't change whether or not it is loaded but will guarantee an error unless you change the association. Before, the error only occurred if you tried to access the association on the particular record.
> Raise error if required association not loaded in preload

- spec/avram/migrator/create_table_statement_spec.cr
- src/avram/migrator/create_table_statement.cr
Fixes #816
When generating a new table and using the `add_timestamps`, this will now generate the `created_at` and `updated_at` columns defaulting to `NOW()`. The values will still come from within Crystal since the SaveOperation will set them, however, this allows you to hop into psql real quick and create a new record without having to worry about setting these.
Updating a record will still require you to update `updated_at` manually since that would require setting up a trigger.
> Add a default value to the default timestamp columns.

- spec/avram/migrator/runner_spec.cr
- src/avram/migrator/runner.cr
> Adding a unique index to migrations

- src/avram/errors.cr
* Added constructor arguments as properties
* Made `InvalidOperationError` generic since there seems no common parent class for operations
* Is there a better way in Crystal?
> Errors should have the variables as properties (#819)

- spec/avram/slugify_spec.cr
- src/avram/slugify.cr
Fixes #813
This method will generate a String value that can be used for a slug, but without setting any attribute value for you. This would be more used for an escape hatch than anything. Since it's not passing in the slug column, there's no way to query to know if it's been taken already. This means we can't do the query lookup to ensure the value is unique.
```crystal
before_save do
if title.changed?
slug.value = Avram::Slugify.generate(using: title)
end
validate_uniqueness slug, query: ArticleQuery.new.slug
end
```
> Adding new Slugify.generate method to generate a slug value

- spec/avram/validations_spec.cr
- src/avram/validations.cr
Fixes #563
Since you can't allow nil, I've added a method overload that raises a compile-time error letting you know that you can't allow nil with ranges.
> Adding an overload for this validation with a Range

- spec/avram/queryable_spec.cr
- spec/avram/time_criteria_spec.cr
- src/avram/charms/time_extensions.cr
Fixes #727
This makes all `Time` columns store with milliseconds. The tough part is if you're trying to do exact comparison with time, it's a bit harder now, but the benefit is if you need to sort by a time column, you'll get a more accurate sorting. This is especially common with UUID based tables that sort by `created_at`.
Also to note that out of the box default with postgres seems to use this same format for time columns:
```
development=# select now();
now              
-------------------------------
2022-03-12 18:02:14.760713+00
(1 row)
```
> Make all default times store in the DB with milliseconds down to 6point.

- src/avram/errors.cr
Fixes #834
Using Crystal 1.2.2, I wasn't able to compile a Lucky project with this. This PR reverts only the part that added the generic.
> Reverting part of #823 due to a Crystal compiler bug

- .github/workflows/ci.yml
- Dockerfile
- shard.yml
Locks Lucky to Crystal version 1.4.0 or later.
With the release of the new Crystal book being focused on 1.4.0, and shards like Ameba locking to that version, as well as Crystal 1.5.0 is slated to come out in the next 2 months, it makes sense that we start pushing to have everyone use a later version of Crystal. This will also allow us to clean up some code with the assumption that the user is using 1.4.0 or later.
> Lock down Crystal to version 1.4 or later

- Dockerfile
This PR fixes (or at least tries to fix) an issue that I had while running on main branch the `script/setup` command.
First issue that i found was 
`gnupg, gnupg2 and gnupg1 do not seem to be installed`
and adding it was resulting into this error:
```
#6 57.14 The following packages have unmet dependencies:
#6 57.43  postgresql-11 : Depends: libicu60 (>= 60.1-1~) but it is not installable
#6 57.43                  Recommends: sysstat but it is not going to be installed
```
This issue was not present in v0.23, so my guess is that the crystal image from v1.0 to v1.4 moved from Bionic Beaver to Focal Fossa, thus invalidating the postgresql repo.
```
root@c39583203fd7:/data# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```
*HOWEVER*, I am not able to still run the …
> Make script/setup work for main branch on crystal v1.4.0

- spec/avram/migrator/alter_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/columns/base.cr
Fixes #791
This adds a new `change_default` macro since you couldn't add a default when calling `change_type`. Before that would just throw an error saying "duplicate argument". Now it'll tell you to use the `change_default` macro instead.
```crystal
alter table_for(Message) do
change_default visible : Bool, default: true
end
```
> Fix default call on change_type. Added new change_default

- db/migrations/20200324211956_create_issue.cr
- spec/avram/type_extensions/enum_spec.cr
- spec/support/factories/issue_factory.cr
- spec/support/models/issue.cr
- src/avram/charms/enum_extensions.cr
Fixes #825
This allows you to specify an `Int64` enum in your model for use with things like bitwise permissions. It also allows enums to be supported on cockroachdb.
> Added the ability to specify Int64 enums for use with Flags. 

- spec/avram/time_criteria_spec.cr
- src/avram/charms/time_extensions.cr
- src/avram/chrono_units.cr
- src/avram/criteria_extensions/extract_criteria.cr
This PR concerns the extract info from date mentioned in issue #857.
It provides a way to be able to extract specific fields from a `timestamptz` column and compare it with some numerical values.
For all the fields implemented till now (see `Avram::ChronoUnits` in the `extract_criteria.cr` or the relevant postgresql documentation), three possible methods are provided:
- `column.extract(Avram::ChronoUnits::<enum_value>)`
e.g: `some_table.created_on.extract(Avram::ChronoUnits::Day)`
- `column.extract(<enum_value_as_symbol>)`
e.g: `some_table.created_on.extract(:day)`
- `column.extract_<enum_value>`
e.g: `some_table.created_on.extract_day`
Functionality can be used as:
- column.extract_year.eq(2022)
Most values returned are ints, but 4 of them which return floats
- julian
- epoch
- second
- …
> Add extract functionality as a new criteria to timestamptz columns

- db/migrations/20220720013254_create_beats.cr
- spec/avram/operations/save_operation_spec.cr
- spec/avram/queryable_spec.cr
- spec/avram/type_extensions/bytes_spec.cr
- spec/support/factories/beat_factory.cr
- spec/support/models/beat.cr
- src/avram/blank_extensions.cr
- src/avram/charms/slice_extensions.cr
- src/avram/migrator/columns/bytes_column.cr
- src/avram/migrator/create_table_statement.cr
Fixes #762
Questions I need an answer for:
* How do you query for this in raw postgres? Postgres will let you query by the original string, or a hexbytes representation. I couldn't get the hexbytes query to work, but regular bytes and the raw string both work.
* What does an insert SQL with this column type look like? `values ('raw string')` or `values ('\xabc123')`. 
* How would you use this in a HTML form or API? I assume you'd pass a String and then call `to_slice`?  You can just use a normal text field and insert a string like a normal String field. Postgres will handle the conversion under the hood.
> Adding support for bytea columns with Bytes

- spec/avram/operations/save_operation_spec.cr
- src/avram/needy_initializer_and_delete_methods.cr
- src/avram/needy_initializer_and_save_methods.cr
Fixes #764
This flips extracting param values first before setting named args. There could be a case where you might have a "admin" field that's technically permitted, but you want the initial value to be `false`. So you set a named arg value to be false. Currently, if a user updated the params to manually push that through, it would be set to what they set it to. Now it'll be set to your named arg value.
> Allows named args to take precendence over param values.

- spec/lucky/ext/input_helpers_spec.cr
- src/lucky/ext/input_helpers.cr
Fixes #851
Since the `checkbox` method is designed to work with Bool values, this one works with Array attributes.
```crystal
values.each do |value|
grouped_checkbox(op.values, value, class: "inline")
end
```
> New grouped_checkbox method for use with Array attributes

- src/lucky/ext/input_helpers.cr
The method used to be called `fill_attribute` or something like that, but we never updated the error message. 
Ignore the branch name... it was an attempt to fix #850 which turned out to be irrelevant.
> fixing this typo

- spec/avram/factory_spec.cr
- spec/support/factories/line_item_factory.cr
- src/avram/factory.cr
Fixes #865
You can now use these like this:
```crystal
class UserFactory < Avram::Factory
def with_friends
after_save do |user|
FriendFactory.create &.user_id(user.id)
end
end
end
UserFactory.create &.with_friends
```
> Factory callbacks now return self

- spec/avram/json_column_spec.cr
- src/avram/charms/json_extensions.cr
Fixes #877
This hasn't really caused issues for people because `JSON::Any` wrapping `nil` still returns true for `.nil?` which seems weird.
> Don't wrap nil in JSON::Any on nilable columns

- spec/lucky/ext/avram/errors_spec.cr
- src/avram/errors.cr
- src/lucky/ext/avram/errors.cr
This is the second time I've attempted this PR and had to revert it... It's a bit complicated to explain, but I'll try....
Related: https://github.com/crystal-lang/crystal/issues/12472
This PR was originally intended to add an escape hatch for a user that wanted to customize the error message in the case of displaying an alternate language. They wanted access to the operation to customize what it said and have it in another language. To do this, we needed to make the error a Generic since you could have several different types of operations; however, there is a bug in Crystal that would cause the compiler to tank.
Originally I was able to fix this by telling the generated Lucky apps in `Errors::Show` action that the render call just assigned `forall T`. I made a comment here …
> Revert #868

- db/migrations/20221015145114_create_tokens.cr
- spec/avram/operations/define_attribute_spec.cr
- spec/avram/operations/operation_needs_spec.cr
- spec/avram/params_spec.cr
- spec/support/models/token.cr
- src/avram/params.cr
Fixes #884
You can now instantiate `Avram::Params` passing a hash with array values or string values or a mixture of both.
> Fix error --  cast from Array(String) to String

- spec/lucky/ext/select_helpers_spec.cr
- src/lucky/ext/select_helpers.cr
Fixes #896 
The other method overload calls `.to_s` on both values because it uses `Avram::PermittedAttribute#param` instead of `Avram::PermittedAttribute#value`. The difference is that `#param` only provides string values while `#value` is the same type as the attribute (but always nilable).
> Compare array attribute values for select options correctly

- spec/lucky/ext/avram/operation_params_spec.cr
- src/avram/add_column_attributes.cr
Fixes #891 
This avoids the situations where you don't have any `permit_columns` and the request data isn't what the operation is normally expecting. This is the case when you are only submitting a file and no other form data.
> Don't extract params if no permitted columns

- db/migrations/20170127143151_create_sign_in_credentials.cr
- spec/avram/preloading/preloading_belongs_to_spec.cr
- spec/avram/preloading/preloading_has_many_spec.cr
- spec/avram/preloading/preloading_has_many_through_spec.cr
- spec/avram/preloading/preloading_has_one_spec.cr
- spec/support/factories/sign_in_credential_factory.cr
- spec/support/models/sign_in_credential.cr
- src/avram/associations.cr
- src/avram/associations/belongs_to.cr
- src/avram/associations/has_many.cr
- src/avram/associations/has_one.cr
This updates the class-level preload functions to check if the association has already been loaded before redoing the process. Now you don't have to worry about making unnecessary SQL queries when you don't have to.
**TODO** Support has many through passing multiple records.
Honestly, has many through has been the most difficult part of the codebase **by far** and this is no different. The problem is when the intermediary association is loaded but not the one in the has many through. Since we pass that we want the has many through association preloaded in the query that loads the intermediary, if it is loaded that call to preload is completely ignored.
The fix is to rethink how we make that query. Instead of loading the intermediaries, just set up fancy joins to only query for the has …
> Avoid re-fetching associations that have already been preloaded

- src/avram/queryable.cr
CockrochDB returns Int64 when checking for email. This fixes that bug.
> Add support for CockrochDB query return

- spec/avram/operations/save_operation_spec.cr
- src/avram/save_operation.cr
Implements #888.
Adds two new boolean methods to `SaveOperation`.
They work similarly to `new_record?` but always return false if the record was not persisted (e.g: failed save or not-yet-performed operation)
> Add updated? and created? methods on SaveOperations

- src/avram/charms/int16_extensions.cr
- src/avram/charms/int32_extensions.cr
- src/avram/charms/int64_extensions.cr
Related to #920
```
cast from PG::Numeric to (Int64 | Nil) failed, at /path/to/lib/avram/src/avram/charms/int32_extensions.cr:51:9:51 (TypeCastError)
from lib/avram/src/avram/charms/int32_extensions.cr:51:9 in 'select_sum'
from lib/avram/src/avram/charms/int32_extensions.cr:55:9 in 'select_sum!'
```
> Fix `TypeCastError` with `#select_sum` in CockroachDB

- spec/avram/migrator/alter_table_statement_spec.cr
- spec/avram/migrator/create_table_statement_spec.cr
- src/avram/migrator/columns/int32_column.cr
- src/avram/migrator/columns/primary_keys/int32_primary_key.cr
Fixes #919
There's no specs, though; can't think of any.
> Fix `DB::ColumnTypeMismatchError` for `Int32` columns in CockroachDB

- shard.yml
- src/avram/version.cr
At this point, I don't think anything is holding back just calling it 1.0.0. There's been several fixes and additions to really make this version more solid. We can now lock in this interface and start thinking about changes to the structure for a 2.0 in the future.
> Release v1.0.0

- src/avram/migrator/migration.cr
- src/avram/migrator/runner.cr
Fixes #937
The initializer of `Avram::Migrator::Runner` re-configures the avram logger to be level `:none`. The runner is instantiated in development during `start_server.cr` to ensure that migrations have been run (after configuration has been loaded). The change was introduced in https://github.com/luckyframework/avram/pull/780
I am assuming the intention was to suppress the logging when the migrator is checking if migrations have run, creating schema tables etc. Instead I have added `suppress_logging` method that uses dexter to temporarily set the level to `:none` and reset after. There might be a nicer way of doing this but there doesn't appear to be a single entrypoint into the migrator that can be configured.
> Suppress logging in migrator

- config/database.cr
- spec/avram/migrator/runner_spec.cr
- spec/avram/tasks/db_create_spec.cr
- spec/avram/tasks/db_schema_restore_spec.cr
- spec/spec_helper.cr
- src/avram/connection.cr
- src/avram/credentials.cr
- src/avram/database.cr
- src/avram/migrator/runner.cr
Fixes #926
This doesn't fully remove the need for it, but it does remove the need for it when doing `db.create` and `db.drop` tasks.
The two main areas still remaining are `db.schema.dump` and `db.schema.restore` tasks which currently require `psql` and `pg_dump` to exist. I would like to somehow catch those and raise some sort of error before you run them. Right now if you don't have pg client tools installed and try to run either of those, you'll just end up with some exceptions saying it couldn't find those commands. Not horrible, but not great...
After doing this, there was some weird things that came up. Previously you could do this:
```crystal
SomeDatabase.run do |db|
db.exec "SELECT some_sql"
end
DB::Drop.run_task
```
That seemed to be ok maybe because it was running `dropdb` from …
> Removes the need for pg client tools

- db/migrations/20230624134902_add_json_array_to_blob.cr
- spec/avram/json_column_spec.cr
- spec/avram/queryable_spec.cr
- spec/support/factories/blob_factory.cr
- spec/support/models/blob.cr
- src/avram/add_column_attributes.cr
- src/avram/charms/json_extensions.cr
Fixes #845
This PR allows you to convert your json arrays in to an array of serialized objects.. One thing to note about this PR is that it's only supporting `'[]'::jsonb` and *not* `[]::jsonb[]`. The distinction here is that the column is still stored as `jsonb`, but it allows that json string to be parsed as an array VS using postgres's ARRAY column to store an array of jsonb objects.
I think we could eventually do that one too by just saying that the column isn't serialized, but that can be for a future PR.
With this, you can now do something like:
```crystal
struct Server
include JSON::Serializable
property host : String
end
class Monitor < BaseModel
table do
column input_server : Server
column output_servers : Array(Server)
end
end
in_server = Server.from_json(%({"host":"x.y.z"})) …
```
> Adding JSON serialized Array columns

- spec/avram/operations/save_operation_spec.cr
- src/avram/upsert.cr
Fixes #864
This fixes an issue when using `upsert` where you may want to update a field's value to `nil` when the record is found.
/cc. @franciscoGPS
> Fixing upsert so you can update a field to nil.

- spec/avram/validations_spec.cr
- src/avram/validations.cr
Fixes #907
This allows us to use `validate_size_of` on Array attributes as well as String.
> Add validate_size_of for array attributes. 

- spec/avram/custom_sql_spec.cr
- spec/support/queries/custom_price_query.cr
- src/avram.cr
- src/ext/pg/numeric_float_converter.cr
Fixes #955
This add a PG extension to convert `PG::Numeric` to `Float64`. Can be used for custom SQL queries.
> Adding new PG extension for auto converting Numeric to Float. 

- src/avram/save_operation.cr
Just a tiny PR but I noticed that for each update and insert it is calling `update_query` and `insert_sql` respectively twice rather than re-using the same generated object.
> Reuse query builder and insert

- spec/spec_helper.cr
- src/avram.cr
Fixes #966
Normally this is enabled the instant you `require "avram"`, but this means you don't have an option to disable this. I think a better spot for your Lucky apps would be to just add that line to your `config/log.cr`. Then if you want to skip these logging events, you can just remove that line. 
This is technically a "breaking change", but it's an easy fix for anyone that needs it just by adding 
```
Avram.initialize_logging
```
somewhere at the start of your app.
> Removing the default logging initializing for flexibiltiy

- spec/lucky/ext/select_helpers_spec.cr
- src/lucky/ext/select_helpers.cr
Fixes #977
All of the Lucky HTML methods allow for boolean attributes, but the `select_input` and `multi_select_input` were missing them.
```crystal
select_input op.theme, attrs: [:disabled] do
end
```
> Adding missing boolean attributes arg for select input methods.

- src/avram/database.cr
Fixes `DB::ConnectionLost` errors.
Closes #989
> Retry lost connections

- spec/avram/database_cleaner_spec.cr
- src/avram/database.cr
- src/avram/spec_helper.cr
> Add missing parameters to `Avram::Database.truncate` method

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/create_table_statement.cr
This fixes some deprecation warnings that came up in the CI from Github Actions and Crystal 1.10 deprecation before Crystal 1.11
> Fix deprecation warnings

- spec/lucky/ext/select_helpers_spec.cr
- src/lucky/ext/select_helpers.cr
> Adds the HTML id in to the select. 

- spec/avram/migrator/alter_table_statement_spec.cr
- spec/avram/migrator/create_table_statement_spec.cr
- spec/avram/migrator/migration_spec.cr
- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/create_table_statement.cr
- src/avram/migrator/statement_helpers.cr
Fixes #988
This adds in the option to specify `if_not_exists` for the `create` table macro and `if_exists` for the `alter` table macro
```crystal
def migrate
create :reports, if_not_exists: true do
end
end
def migrate
alter :reports, if_exists: true do
end
end
```
> Adding IF EXISTS and IF NOT EXISTS for migrations

- spec/avram/preloading/preloading_has_many_spec.cr
- spec/avram/preloading/preloading_has_one_spec.cr
- src/avram/associations/has_one.cr
Fixes #985
The `has_many` and `belongs_to` both have a preload override method that takes a block and passes in the `BaseQuery` object. The `has_one` was missing it.
This lets you do something like
```crystal
class User < BaseModel
table do
has_one theme : Theme
end
end
UserQuery.new.preload_theme(&.with_soft_deleted)
```
> Adding block override for preloading with has_one.

- spec/avram/tasks/db_verify_connection_spec.cr
- spec/spec_helper.cr
- src/avram/tasks/db/verify_connection.cr
Fixes #902
We've had users in the past that get started with Lucky and have a horrible first experience because their setup script never completes. In this last case, it was only the `verify_connection` task that was failing, but not very apparent. We used to have the code work this way, but changed it to call `open.close`. Somehow, that must be causing some sort of race condition and randomly fails for some people.
I wasn't ever able to recreate the issue, but I'd rather give people a nice first experience, so I'm just reverting this for now.
> Revert and cleanup the verify_connection task

- src/avram/migrator/runner.cr
Fixes #440
Now that we removed the pg client tools requirement, the only 2 commands that still require external programs are `restore_db` and `dump_db`. If you used either of these, and your DB config had special shell characters, things could get a little wonky.
This PR adds a bit of safety by removing the `shell: true`, and pushing the args in separately. It also cleans up the shell commands to not use `<` , `>`, and `>>` and just use `File.open`.
> Remove use of shell in Process.run

- spec/avram/queryable_spec.cr
- src/avram/query_builder.cr
Fixes #827
This changes the syntax of the `UPDATE` sql so when you have a join, it moves the whole `WHERE` clause to a subquery.
Previously, if you tried to bulk update with a join, it would throw a postgres syntax error
```
UPDATE ... SET x = 1 INNER JOIN.....
```
Now this moves it to a subquery with
```
UPDATE ... SET x = 1 WHERE EXISTS (.... INNER JOIN ....);
```
> Wrapping update queries with joins in a subquery

- spec/avram/migrator/alter_table_statement_spec.cr
- spec/avram/migrator/create_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
- src/avram/migrator/create_table_statement.cr
Fixes #999
When using `add_belongs_to` in migrations, it creates an index by default, but if you need an escape hatch to skip that, you can now pass `index: false`. 
```crystal
add_belongs_to user : User, on_delete: :cascade, index: false
```
> Allow skipping the index when using add_belongs_to in migrations

- spec/avram/migrator/create_sequence_statement_spec.cr
- spec/avram/migrator/drop_sequence_statement_spec.cr
- spec/avram/migrator/migration_spec.cr
- src/avram/migrator/create_sequence_statement.cr
- src/avram/migrator/drop_sequence_statement.cr
- src/avram/migrator/statement_helpers.cr
Fixes #910
This adds new `create_sequence` and `drop_sequence` migration helpers.
```crystal
def migrate
create_sequence table_for(Account), :number
end
def rollback
drop_sequence table_for(Account), :number
end
```
> Adding create_sequence and drop_sequence migration helpers.

- spec/avram/float_criteria_spec.cr
- spec/avram/integer_criteria_spec.cr
- spec/avram/string_criteria_spec.cr
- src/avram/charms/float64_extensions.cr
- src/avram/charms/int16_extensions.cr
- src/avram/charms/int32_extensions.cr
- src/avram/charms/int64_extensions.cr
- src/avram/charms/string_extensions.cr
I was having a little fun and decided to add just a few more I thought may be helpful.
This adds a few extra Criteria functions
* LENGTH()
* REVERSE()
* ABS()
* CEIL()
* FLOOR()
```crystal
UserQuery.new.username.length.eq(6)
UserQuery.new.secret.reverse.eq("terces")
TransactionQuery.new.amount.abs.eq(400)
PurchaseQuery.new.amount.ceil.eq(40.0)
PurchaseQuery.new.amount.floor.eq(30.0)
```
> More criteria functions

- spec/avram/join_spec.cr
- src/avram/join.cr
Fixes #1007
This gives you a way to set an alias for the join table when building `Avram::Join` directly.
> Give Join a way to alias the joining table.

- db/migrations/20240224173636_create_transactions.cr
- db/migrations/20240225160631_create_follows.cr
- spec/avram/preloading/preloading_has_many_spec.cr
- spec/avram/preloading/preloading_has_many_through_spec.cr
- spec/avram/queryable_spec.cr
- spec/support/factories/follow_factory.cr
- spec/support/factories/transaction_factory.cr
- spec/support/models/follow.cr
- spec/support/models/transaction.cr
- spec/support/models/user.cr
- src/avram/associations/has_many.cr
- src/avram/model.cr
Fixes #85
This PR adds a new arg that allows you to set the query class used for querying your association. This can be used in conjunction with soft_deleted records to ensure every preload you do only preloads the kept records.
```crystal
class User < BaseModel
table do
has_many transactions : Transaction, base_query_class: TransactionQuery
has_many follows : Follow, foreign_key: :followee_id, base_query_class: FollowQuery
has_many followers : User, through: [:follows, :follower]
end
end
class TransactionQuery < Transaction::BaseQuery
include Avram::SoftDelete::Query
def initialize
defaults &.only_kept
end
end
UserQuery.new.preload_transactions
```
The default base_query_class is always `T::BaseQuery`, but with soft_deleted models, you would have to either monkey-patch `T::BaseQuery`, or …
> Adding new base_query_class arg for associations.

- spec/avram/json_criteria_spec.cr
- src/avram/charms/json_extensions.cr
- src/avram/where.cr
Ref #197
This PR adds in 3 new criteria method for `JSON::Any` columns
* `has_key` which performs `WHERE jsonb ? 'some_key'`. 
* `has_any_keys` which performs `WHERE jsonb ?| '{"this_key", "or_that_key"}'`
* `has_all_keys` which performs `WHERE jsonb ?& '{"this_key", "and_this_key"}'`
This makes doing queries on JSON columns a little easier since you can't do raw WHERE queries on these because they use the `?` character which the PG shard uses as a placeholder [ref](https://github.com/luckyframework/avram/issues/939)
```crystal
class User < BaseModel
table do
column preferences : JSON::Any
end
end
UserQuery.new.preferences.has_key("theme")
UserQuery.new.preferences.has_any_keys(["theme", "color_mode"])
UserQuery.new.preferences.has_all_keys(["theme", "style"])
```
*Side note*: I'm not …
> Adds new JSON::Any criteria methods for querying jsonb columns

- spec/avram/json_criteria_spec.cr
- src/avram/charms/json_extensions.cr
- src/avram/where.cr
Fixes #197 
This PR adds 2 more query methods following #1015
* `includes` which performs `WHERE jsonb @> '{"some":"json"}'`
* `in` which performs `WHERE jsonb <@ '{"some":"json"}'`
Also while I was in there I decided to rename the previously added Where classes from `JSON..` to `Jsonb...`. While reading the class names that seemed to make it a little more clear for me.
```crystal
class User < BaseModel
table do
column preferences : JSON::Any
end
end
UserQuery.new.preferences.includes(JSON::Any.new({"theme" => JSON::Any.new("dark")}))
UserQuery.new.preferences.in(JSON::Any.new({"theme" => JSON::Any.new("dark")}))
```
> Adds 2 new JSON critera query methods

- src/avram.cr
- src/avram/attribute.cr
- src/avram/base_query_template.cr
- src/avram/needy_initializer.cr
- src/avram/needy_initializer_and_delete_methods.cr
- src/avram/needy_initializer_and_save_methods.cr
- src/avram/nothing.cr
Fixes #1017
This PR adds a single `Avram::Nothing.new` instance assigned to a new constant called `IGNORE`. This does 2 things
1. Uses a single allocated instance everywhere to represent `Avram::Nothing` instead of a new instance for every column. While this doesn't give a ton of memory savings, it's still better
2. For those nasty overload errors, it shrinks them up by a few characters.  
Before:
After:
> Added new `Undefined` constant

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- Dockerfile
- docker-compose.yml
- shard.yml
While there's no breaking changes back to 1.6.2, I don't think we need to continue supporting the older Crystal versions with 1.12 released, and 1.13 well in the works. 
Since I was in here, I decided to also bump the postgres versions. We've been testing against 12, 13, and 14, but 15 and 16 are both out with 17 in the works.
> Updating min Crystal and postgres versions

- src/lucky/tasks/gen/templates/resource/pages/edit_page.cr.ecr
- src/lucky/tasks/gen/templates/resource/pages/index_page.cr.ecr
- src/lucky/tasks/gen/templates/resource/pages/show_page.cr.ecr
1. links use non keyword argument form.
2. Remove unnecessary namespaces.
> Refine CRUD templates

- spec/avram/queryable_spec.cr
- src/avram/criteria.cr
Fixes #1038 .
Basically, when we are doing a PG:something -> SomethingElse conversion, it usually works as long as you can cast safely from one another.
Eg: 1 (PG::Int) can be cast to int with .as(Int). Same for strings
However that is not the case for Numeric values - for them the simple .as(Float) does not work - but we need to get through the .to_f method.
This pull request does exactly this, it adds one new method (to_expected_type) with one overload in the specific case of the input being a PG::numeric.
It also fixes the select_max, which was having the same issue
> Fixes #1038: type cast fails in select_min/max

- spec/avram/migrator/alter_table_statement_spec.cr
- src/avram/migrator/alter_table_statement.cr
This PR attempts to fix two things:
Related to #1039 
Two new macros have been created:
- allow_nulls_for :column, which allows for the :column to receive null values
- forbid_nulls for :column, which set the not null constraint
it is split from the change_type statement, so that you can theoretically do something like
```
change_type the_column : String
forbid_nulls_for :the_column
```
Currently, if you had something like:
```
change_type a : String
change_default a : String, default: "Whatever"
```
it would generate first the change of default, then the change of type, which is probably counterintuitive.
Now, it generates first the change of type, then the change of default
> Add change nullability statement

- spec/avram/array_column_spec.cr
- spec/avram/migrator/alter_table_statement_spec.cr
- spec/avram/where_spec.cr
- src/avram/criteria.cr
- src/avram/migrator/alter_table_statement.cr
- src/avram/where.cr
Implements the feature in #1030 
However, the method was renamed to `have_any?`, instead of `has_any`, just because an array column will prolly be called in the plural form (e.g: `Users.tags`) and have_any just sounded better.
> Add have any criteria

- spec/avram/migrator/drop_table_statement_spec.cr
- src/avram/migrator/drop_table_statement.cr
- src/avram/migrator/statement_helpers.cr
- Implements #1037 
- Adds a ";" - I'm not sure about that one, though
> Add if-exists clause to drop table

- src/avram/tasks/gen/migration.cr
- src/avram/tasks/gen/migration_generator.cr
Test on both CamelCase and underscore form, it should work.
```
╰─ $ lucky gen.migration add_some_column_into_universities
Created AddSomeColumnIntoUniversities::V20240524171815 in ./db/migrations/20240524171815_add_some_column_into_universities.cr
```
```
╰─ $ lucky gen.migration AddSomeColumnIntoUniversities
Created AddSomeColumnIntoUniversities::V20240524172255 in ./db/migrations/20240524172255_add_some_column_into_universities.cr
```
BTW: i remove the CamelCase check completely, i consider those code is unnecessary, if a user can user task to create migration, we assume it know how to form the migration name.
> Support camelcase when generate migration file, Fix #1045

- spec/avram/query_builder_spec.cr
- src/avram/where.cr
Implements #1031 
Btw, is there any reason for which the raw does param substitution and does not use bind variables? Albeit small, there might be a perf hit, in that case
> manage raw where clause with array as param

- .github/workflows/ci.yml
- shard.override.yml
Closes #1025
The issues are actually related to Habitat and Lucky, but since this shard has dependencies on them, it also started failing. Now that those shards have been resolved, we can test using them to make sure all of these specs turn green again.
> Fixing Crystal nightly issues related to upcoming 1.13

- src/avram/errors.cr
Fixes #983
I just got bit by this again. If your default user is `postgres`, you generally already have a database called `postgres`; however, in the case of Avram specs, we use the user `lucky`. This means you have to have a local db call `lucky` in order to run `lucky db.create`. This is because when we removed the `pg_client` dependency we no longer have access to `createdb`. Instead, we have to connect to the DB server and run some SQL... but postgres doesn't let you connect to the server without being attached to some database.. :chicken: :egg: :man_shrugging:  
This PR just adds an error message that tells you
> ▸ If this is your first run, create a database named 'lucky' that this same user will have access to
That should at least point to a common fix for this problem.
> Adding a helpful error message for "Could not connect"

- spec/avram/validations_spec.cr
- src/avram/i18n_backend.cr
- src/avram/validations.cr
Fixes #667
Adds new `validate_url_format` validator.
> Adding new validation to validate URL formatted attributes

- src/avram/add_column_attributes.cr
- src/avram/attribute.cr
Even if nested params is not empty, Lucky would still raise `Lucky::MissingNestedParamError` if any array attributes are not set.
You had to fill in the array attribute to avoid the error:
```crystal
response = client.exec(Features::Create, feature: {
choices: Array(String).new, # Without this, you get "Missing param key: 'feature' (Lucky::MissingNestedParamError)..."
maximum: 99,
minimum: 3,
name: "Number of Kitchens",
type: :integer
})
```
See <https://github.com/luckyframework/lucky/issues/1949>
> Fix missing nested param error for nested array params

- spec/avram/associations_spec.cr
- spec/avram/query_associations_spec.cr
- spec/avram/queryable_spec.cr
- src/avram/base_query_template.cr
This deprecates `#where_*` join methods to which the query condition was delegated.
Closes #1088
> Add join method overloads that accept the query condition as argument

- src/avram/database.cr
- src/avram/query_builder.cr
- src/avram/queryable.cr
- src/avram/table_lock_mode.cr
Fixes #594
This adds some options for doing table and row locks.
```crystal
AppDatabase.with_lock_on(User, mode: :row_exclusive) do
user = UserQuery.new.id(1).for_update.first
SaveUser.update!(user, name: "New Name")
end
```
Testing it in a real app, and it seems to work... I'm not sure how to test this other than just ensuring the correct SQL is generated.
> Adding table locking.

- spec/avram/operations/delete_operation_spec.cr
- spec/avram/operations/save_operation_spec.cr
- src/avram/delete_operation.cr
- src/avram/save_operation.cr
Fixes #1101
Previously we had delegated the `database` method to the model, but that method won't always exist now since splitting them in to read/write access. This PR adds the method back in as a helper method to avoid breaking changes with existing apps.
> Adding the database method back in to Save and Delete operations

- spec/avram/operations/save_operation_spec.cr
- src/avram/save_operation.cr
> Fix `Avram::SaveOperation#new_record?` for when id is set explicitly

- spec/avram/factory_spec.cr
- src/avram/factory.cr
Fixes #1113
Adds a new `create_many` factory method that essentially works the same as `create_pair` but allowing you to specify the number you want to create. Then `create_pair` just proxies to `create_many(2)`.
```crystal
TagFactory.create_many(3)
TagFactory.create_many(3, &.name("test"))
```
> Adding new create_many factory method
