luckyframework/avram

Dockerfile, config/database.cr, shard.yml, spec/form_spec.cr, src/avram.cr, src/avram/form.cr, src/avram/needy_initializer_and_save_methods.cr, src/avram/repo.cr
=> Log when form fails to save

spec/query_builder_spec.cr, spec/query_spec.cr, src/avram/query_builder.cr
=> fix order by direction

spec/virtual_form_spec.cr, src/avram/form.cr, src/avram/form_errors.cr, src/avram/virtual_form.cr
=> Add `VirtualForm#errors`

spec/form_needs_spec.cr, spec/form_spec.cr, spec/migrator/alter_table_statement_spec.cr, spec/migrator/create_table_statement_spec.cr, spec/model_spec.cr, spec/support/boxes/scan_box.cr, spec/support/boxes/user_box.cr, spec/time_criteria_spec.cr, spec/type_extensions/bool_spec.cr, spec/type_extensions/time_spec.cr, spec/type_extensions/uuid_spec.cr, src/avram/form.cr, src/avram/tasks/gen/migration.cr
There a couple of relative paths used in `require`s that needs to be fixed for Crystal 0.29.0
=> Updates for crystal 0.29.0

spec/criteria_spec.cr, src/avram/criteria.cr
=> Fix nilable eq

config/database.cr
=> Remove hack now that 0.29 fixes the issue

spec/nested_save_operation_spec.cr, spec/save_operation_spec.cr, spec/virtual_operation_spec.cr, spec/virtual_spec.cr, src/avram/param_key_override.cr, src/avram/save_operation.cr, src/avram/virtual_operation.cr
Underscore class and name for  VirtualOperation
Closes #102
=> Use underscored model class as param_key

spec/define_attribute_spec.cr, spec/nested_save_operation_spec.cr, spec/operation_needs_spec.cr, spec/preloading_spec.cr, spec/save_operation_callbacks_spec.cr, spec/save_operation_spec.cr, spec/transaction_spec.cr, spec/type_extension_spec.cr, spec/validations_spec.cr, spec/virtual_operation_spec.cr, src/avram/box.cr, src/avram/errors.cr, src/avram/needy_initializer_and_save_methods.cr, src/avram/save_operation.cr
=> Rename form -> operation

spec/query_associations_spec.cr, src/avram/associations/has_many.cr, src/avram/base_query_template.cr
=> Prefix association queries with `where_`

src/avram/base_query_template.cr
=> Raise helpful error for old association method

spec/query_builder/merge_spec.cr, spec/query_builder_spec.cr, src/avram/query_builder.cr
=> Merge queries

spec/query_associations_spec.cr, src/avram/associations/has_many.cr, src/avram/base_query_template.cr
Fixes #143 (as far as the new issues I've found 😅 )
=> Fixing issue with name spaced models

spec/criteria_spec.cr, src/avram/criteria.cr, src/avram/queryable.cr
With fancy error handling
Also clarified the  other error  message:
Closes #184
=> Add is_nil and is_not_nil

spec/query_builder_spec.cr, spec/query_spec.cr, src/avram/query_builder.cr, src/avram/queryable.cr
Closes #191 
This also makes sure order bys are unique
=> Reset order

spec/spec_helper.cr, src/avram/tasks/db/verify_connection.cr
=> Print "Done" when connection is verified

db/migrations/20190723233131_test_change_type.cr, spec/migrator/alter_table_statement_spec.cr, src/avram/migrator/alter_table_statement.cr, src/avram/migrator/columns/base.cr
=> Add change_type

spec/query_logging_spec.cr, spec/save_operation_spec.cr, src/avram.cr, src/avram/pool_statement_logging.cr, src/avram/save_operation.cr
=> Allow logging SQL and customizing save failed log level

src/avram/migrator/runner.cr
You get a weird error like this: `createdb: could not connect to database template1: could not connect to server: No such file or directory`
This PR helps people figure out what to do
=> Better error when Postgres not running

shard.yml, src/avram/version.cr
This includes a number of bug fixes and a couple new features:
* New log level options
* Allow logging the query
* Allow cloning queries
=> Bump version to v0.11.1

spec/save_operation_spec.cr, src/avram/errors.cr, src/avram/save_operation.cr
=> Clarify InvalidOperationError

spec/define_attribute_spec.cr, spec/save_operation_spec.cr, src/avram/define_attribute.cr, src/avram/save_operation_errors.cr
=> Return all attributes

src/avram/schema_enforcer.cr
The tolerance of 4 was too high. It suggested "id" for "email"...2 seems to work pretty well
=> Make  SchemaEnforcer tolerance a bit less tolerant

src/avram/tasks/db/create.cr, src/avram/tasks/db/drop.cr, src/avram/tasks/db/migrate.cr, src/avram/tasks/db/migrate_one.cr, src/avram/tasks/db/migrations_status.cr, src/avram/tasks/db/redo.cr, src/avram/tasks/db/rollback.cr, src/avram/tasks/db/rollback_all.cr, src/avram/tasks/db/rollback_to.cr, src/avram/tasks/db/schema_dump.cr, src/avram/tasks/db/schema_restore.cr, src/avram/tasks/db/verify_connection.cr, src/avram/tasks/gen/migration.cr, src/precompiled_tasks/gen/migration.cr
Also makes it so gen.migration prints a help message
Part of https://github.com/luckyframework/lucky/issues/787
=> Add lots of help messages

src/avram/tasks/db/create.cr, src/avram/tasks/db/drop.cr, src/avram/tasks/db/migrate.cr, src/avram/tasks/db/migrate_one.cr, src/avram/tasks/db/redo.cr, src/avram/tasks/db/rollback.cr, src/avram/tasks/db/rollback_all.cr, src/avram/tasks/db/rollback_to.cr, src/avram/tasks/db/schema_dump.cr, src/avram/tasks/db/schema_restore.cr, src/avram/tasks/db/verify_connection.cr, src/avram/tasks/gen/migration.cr
=> Use summary in help messages

db/migrations/20190723233131_test_change_type.cr, shard.yml, spec/type_extension_spec.cr, src/avram/charms/int16_extensions.cr, src/avram/charms/int32_extensions.cr, src/avram/pool_statement_logging.cr, src/avram/query_builder.cr, src/avram/queryable.cr, src/avram/save_operation.cr
=> Support 0.31.1 and upgrade deps

shard.yml, src/avram/version.cr
=> Bump to v0.12.0

spec/type_extensions/int32_spec.cr, src/avram/charms/int32_extensions.cr
=> added cast from int64 to int32

shard.yml, src/avram/version.cr
This update includes several bug fixes, and a new few new methods.
=> 0.12.1 patch update

spec/query_builder_spec.cr, src/avram/queryable.cr, src/avram/where.cr
sometimes you might parse args from dynamic input so this enables you to do that.
=> allow passing bind_args as array to Where::Raw

src/avram/migrator/alter_table_statement.cr, src/avram/migrator/create_table_statement.cr, src/avram/migrator/missing_on_delete_with_belongs_to_error.cr
=> Give better example and link to relevant docs

.gitignore, spec/schema_enforcer_spec.cr, spec/spec_helper.cr, src/avram/model.cr, src/avram/schema_enforcer.cr, tasks.cr
=> Add 'skip_schema_enforcer'

spec/model_spec.cr, src/avram/base_query_template.cr, src/avram/model.cr, src/avram/save_operation_template.cr
=> Add Avram::Model#reload

src/avram/criteria.cr, src/avram/queryable.cr
=> Changed __ prefix to private.

spec/query_spec.cr, src/avram/base_query_template.cr, src/avram/query_builder.cr, src/avram/queryable.cr, src/avram/save_operation.cr
=> Bulk update

spec/operation_needs_spec.cr, spec/save_operation_spec.cr, src/avram/needy_initializer_and_save_methods.cr
=> [BREAKING CHANGE] allow setting attributes from SaveOperation.new, also remove 'on' option for needs

src/avram/criteria.cr
Understanding when to use nilable_eq can be complex. I think have some
scenarios with examples will help.
=> Improve nilable_eq error

shard.yml, src/avram/version.cr
Still needs versions for lucky cli and lucky to be tagged
=> Bump deps and release 0.13.0

script/test, src/avram/tasks/db/setup.cr
=> Adding in new db.setup task to run db.create and db.migrate together

src/avram/model.cr
=> Fix typo in reload model docs

Dockerfile, shard.yml
Need these so specs will pass on Crystal 0.35
=> Updated shards and Dockerfile to support Crystal 0.35.0

spec/database_cleaner_spec.cr, src/avram/database.cr
In reference to https://github.com/luckyframework/avram/issues/425
=> Delete strategy for DatabaseCleaner

.github/workflows/ci.yml, shard.yml, spec/array_column_spec.cr, spec/associations_spec.cr, spec/attribute_spec.cr, spec/define_attribute_spec.cr, spec/lazy_loading_spec.cr, spec/migrator/drop_index_statement_spec.cr, spec/polymorphic_spec.cr, spec/preloading_spec.cr, spec/query_associations_spec.cr, spec/query_spec.cr, spec/save_operation_spec.cr, spec/support/lazy_load_helpers.cr, spec/transaction_spec.cr, spec/type_extensions/time_spec.cr, spec/type_extensions/uuid_spec.cr, src/avram/errors.cr, src/avram/migrator/alter_table_statement.cr, src/avram/migrator/create_index_statement.cr, src/avram/migrator/drop_index_statement.cr, src/avram/query_builder.cr, src/avram/schema_enforcer.cr, src/avram/tasks/db/verify_connection.cr
Closes #431 
The first commit fixes all Ameba issues. The second commit adds Ameba to GitHub Actions, unfortunately I wasn't able to do it with official Ameba Action (https://github.com/crystal-ameba/github-action) because of this issue: https://github.com/crystal-ameba/github-action/issues/8. But we can always revisit configuration later.
=> Fix ameba issues

Dockerfile, shard.yml, src/avram/version.cr
Bumping versions for next release.
=> Release 0.17

spec/operations/nested_save_operation_spec.cr, spec/params_spec.cr, spec/support/fake_params.cr
=> Adding in specs for params has_key_for? method

spec/operations/operation_needs_spec.cr, src/avram/define_attribute.cr
=> Allowing file_attributes to be passed through named args. 

src/avram/associations/has_many.cr
Purely a refactor to simplify the diff of https://github.com/luckyframework/avram/pull/525
=> Refactor has many macro code

src/avram/operation.cr, src/avram/operation_errors.cr, src/avram/save_operation.cr
This just cleans up the operation error stuff.
Ref: https://github.com/luckyframework/avram/pull/469#discussion_r509677459
=> Some simple cleanup on the path to #369

spec/migrator/alter_table_statement_spec.cr, src/avram/migrator/alter_table_statement.cr, src/avram/migrator/create_table_statement.cr
Allow for:
add_belongs_to author : User, unique: true
Updated tests.
=> Allow unique index on belongs to

spec/operations/save_operation_spec.cr
super small PR for this comment https://github.com/luckyframework/avram/pull/540
=> small test update

src/avram/save_operation.cr
Not a very big cleanup. The budget was low for this one.
=> removing some duplicate requires

src/avram/define_attribute.cr
=> Update error message when attribute called with type union

shard.yml
Bumping this to the latest PG release. I have another PR for the array UUID stuff that will need this.
=> bump pg version

db/migrations/20210108124932_add_array_uuid_to_buckets.cr, spec/array_column_spec.cr, spec/support/boxes/bucket_box.cr, spec/support/models/bucket.cr, spec/type_extensions/array_spec.cr, src/avram/charms/uuid_extensions.cr
=> Add support for Array(UUID)

spec/operations/operation_spec.cr, src/avram/operation.cr
=> Do not run operation if invalid

.github/workflows/ci.yml, Dockerfile, shard.yml, src/avram/callbacks.cr, src/avram/credentials.cr, src/avram/factory.cr, src/avram/migrator/statement_helpers.cr, src/avram/primary_key_methods.cr, src/avram/queryable.cr, src/avram/soft_delete/model.cr, src/avram/soft_delete/query.cr
This updates everything to run and build on Crystal 0.36.1
=> crystal 0.36.1 Support

shard.yml, src/avram/version.cr
=> Release 0.19.0

shard.yml, src/avram/version.cr
Just a patch release that includes a few bug fixes
=> Release 0.19.1

spec/migrator/table_for_spec.cr, src/run_macros/infer_table_name.cr
=> Fix table inferrencing for constant-case model names

shard.yml, spec/migrator/migration_spec.cr, src/avram/join.cr, src/avram/migrator/runner.cr, src/avram/paramable.cr, src/avram/query_builder.cr, src/avram/save_operation.cr, src/avram/schema_enforcer/ensure_matching_columns.cr, src/avram/type.cr
A few style suggestions, and some performance suggestions. Hoping to see some green from the CI here.
=> Updates to use the latest ameba.

shard.yml, src/avram/version.cr
This is the release for 0.20.0
=> Release 0.20.0

spec/tasks/db_schema_restore_spec.cr, src/avram/migrator/runner.cr, src/avram/tasks/db/drop.cr, src/avram/tasks/db/reset.cr
PR for Issue: https://github.com/luckyframework/avram/issues/620
=> Added "quiet" option to db.reset and db.drop

src/avram/attribute.cr, src/avram/base_query_template.cr, src/avram/needy_initializer.cr, src/avram/needy_initializer_and_delete_methods.cr, src/avram/needy_initializer_and_save_methods.cr, src/avram/nothing.cr
Fixes #673 
Hopefully the comment on the `Avram::Nothing` class does an ok job at explaining its existence.
=> Consolidate nothing classes into one

shard.yml, src/avram/version.cr
=> Release v0.21.0

spec/operations/save_operation_spec.cr, src/avram/define_attribute.cr, src/avram/needy_initializer_and_save_methods.cr
=> Working out issues with inherited save operations. 

spec/type_extensions/enum_spec.cr, src/avram/charms/enum_extensions.cr
=> Fixing enums when the value looks like an int but is a string

spec/support/models/bucket.cr
Fixes #512
It seems that issue was actually fixed a while ago. I'm adding these defaults in just to ensure that the original bug doesn't come back at some point.
=> Adding defaults to the array columns in Bucket

shard.yml, src/avram/version.cr
This release includes a few bug fixes.
=> Release 0.21.1

db/migrations/20180627220827_create_price_for_line_items.cr, db/migrations/20180628193336_create_line_items_products.cr, db/migrations/20210902161110_create_fake_table_with_uuid_and_no_default.cr, spec/schema_enforcer/ensure_uuid_primary_key_has_default_spec.cr, src/avram/save_operation_template.cr
=> Only set default UUID value on the SQL side

.github/workflows/ci.yml, shard.edge.yml
Ensuring that nothing breaks with latest Lucky or Crystal
=> Adding latest and nightly checks for CI

spec/avram/queryable_spec.cr, src/avram/queryable.cr
Fixes #798 
Thanks to @robacarp for the patch suggestion!
=> Fixing query cache on some methods

shard.yml, src/avram/version.cr
=> Release 0.23.0

.github/workflows/ci.yml, .github/workflows/docs.yml, shard.yml
Adding postgres 14, and locking down Ameba due to Ameba 1.0 compatibility breakage.
=> CI Cleanup

src/avram/migrator/alter_table_statement.cr
=> Fixing error with default and fill_existing_with

src/avram/schema_enforcer/ensure_uuid_primary_key_has_default.cr
=> removing references to uuid-ossp in favor of pgcrypto. 

spec/avram/migrator/alter_table_statement_spec.cr, src/avram/migrator/alter_table_statement.cr
=> Allow change_type to change from one nilable type to another

spec/lucky/ext/avram/errors_spec.cr, src/avram/errors.cr
Fixes #819
Adding this type back in now that Crystal 1.4+ is required.
=> Add access to operation from InvalidOperationError

spec/avram/attribute_spec.cr, src/avram/where.cr
This fixes the annotation warnings from Crystal 1.5
=> fixing warnings from Crystal 1.5

src/lucky/ext/avram/errors.cr
Right now the LuckyCLI is tanking on this class like it did before... I'm hoping it's because this was missed....
=> this update was missed in #868

shard.yml, src/avram/version.cr
Release notes will be added to the Lucky CHANGELOG file
=> Release v1.0.0-rc1

spec/avram/operations/delete_operation_spec.cr, src/avram/needy_initializer_and_delete_methods.cr
=> always pass record to block in a delete operation

db/migrations/20221230233454_create_tasks.cr, shard.yml, spec/avram/operations/save_operation_spec.cr, spec/lucky/ext/avram/operation_params_spec.cr, spec/lucky/support/param_helper.cr, spec/support/factories/task_factory.cr, spec/support/models/task.cr
@stephendolan Here's a spec setup for that issue you closed out... though, it seems to be failing for me :thinking:
=> Adding in a spec that tests Lucky #1762

spec/avram/preloading/preloading_belongs_to_spec.cr, src/avram/associations/belongs_to.cr
=> Fix compile error when preloading optional associations

spec/avram/operations/save_operation_callbacks_spec.cr, spec/avram/query_builder_spec.cr, spec/lucky/ext/input_helpers_spec.cr, spec/lucky/ext/label_helpers_spec.cr, spec/support/cleanup_helper.cr, spec/support/lazy_load_helpers.cr, spec/support/schema_enforcer_helpers.cr, src/avram/database.cr, src/avram/factory.cr, src/avram/migrator/alter_table_statement.cr, src/avram/migrator/create_table_statement.cr, src/avram/migrator/migration.cr, src/avram/migrator/migrator.cr, src/avram/migrator/runner.cr, src/avram/model.cr, src/avram/operation.cr, src/avram/primary_key_methods.cr, src/avram/queryable.cr, src/avram/save_operation.cr, src/avram/tasks/gen/migration.cr, src/lucky/ext/label_helpers.cr, src/lucky/ext/select_helpers.cr
Looks like we're pulling ameba 1.4 now that includes some new suggestions.
=> Applying latest ameba suggestions

shard.yml
=> update to latest DB, PG, and Ameba

spec/avram/operations/save_operation_spec.cr
Ref #914 
@russ I tried to replicate your JSON issue here, but specs are passing, so I'm not sure if maybe this issue was fixed recently, or if I'm missing something with how you were getting that failure...
=> Adding a spec to test #914

db/migrations/20230805212959_add_next_id_to_tokens.cr, spec/avram/operations/save_operation_spec.cr, spec/support/factories/token_factory.cr, spec/support/models/token.cr
Closes #906
It's possible the original issue was fixed by https://github.com/luckyframework/avram/pull/957
=> Adding specs to confirm #906. Seems to be fine.

spec/avram/preloading/preloading_belongs_to_spec.cr, spec/avram/preloading/preloading_has_many_spec.cr, spec/avram/preloading/preloading_has_many_through_spec.cr, spec/avram/preloading/preloading_has_one_spec.cr, src/avram/associations.cr, src/avram/associations/belongs_to.cr, src/avram/associations/has_many.cr, src/avram/associations/has_one.cr
Fixes #941
We already had this method, but it was protected... I'm not sure why, but it seems like a handy method to have public, so this PR makes it public.
=> Adding association_preloaded? method

shard.override.yml, shard.yml, src/avram/tasks/db/console.cr, src/avram/tasks/db/create.cr, src/avram/tasks/db/drop.cr, src/avram/tasks/db/migrate.cr, src/avram/tasks/db/migrate_one.cr, src/avram/tasks/db/migrations_status.cr, src/avram/tasks/db/redo.cr, src/avram/tasks/db/reset.cr, src/avram/tasks/db/rollback.cr, src/avram/tasks/db/rollback_all.cr, src/avram/tasks/db/rollback_to.cr, src/avram/tasks/db/schema_dump.cr, src/avram/tasks/db/schema_restore.cr, src/avram/tasks/db/setup.cr, src/avram/tasks/db/verify_connection.cr, src/avram/tasks/gen/migration.cr
This updates the version to the latest LuckyTask and updates all of the built-in tasks to use this new code. It was mainly just changing how the `help_message` is defined.
=> Updating LuckyTask code

src/avram/database.cr, src/avram/migrator/runner.cr, src/avram/queryable.cr
=> Fix CockroachDB errors

shard.yml, src/avram/version.cr
This release contains
* Bug fix for CockroachDB
* Bug fix for `select_input` using `attrs` property
=> Release v1.1.1

spec/avram/operations/delete_operation_callbacks_spec.cr, src/avram/delete_operation.cr
=> Run delete operation in a transaction

src/avram/migrator/alter_table_statement.cr
=> Fixing docs for change_default.

shard.override.yml, shard.yml, src/avram/version.cr
This is the release for v1.3.0. Changes will be listed in the [CHANGELOG](https://github.com/luckyframework/lucky/blob/main/CHANGELOG.md)
=> Release v1.3.0

.github/workflows/ci.yml, .gitignore, shard.override.yml, shard.yml
Ref: https://github.com/will/crystal-pg/pull/292
=> Testing Windows PG Patch

spec/avram/migrator/runner_spec.cr, spec/avram/operations/nested_save_operation_spec.cr, spec/avram/tasks/db_schema_restore_spec.cr, spec/lucky/support/context_helper.cr, src/avram/credentials.cr, src/avram/database/table_info.cr, src/avram/database_validations.cr, src/avram/events/delete_failed_event.cr, src/avram/events/save_failed_event.cr, src/avram/events/save_success_event.cr, src/avram/generic_attribute.cr, src/avram/join.cr, src/avram/migrator/create_trigger_statement.cr, src/avram/migrator/runner.cr, src/avram/order_by_clause/order_by.cr, src/avram/query_builder.cr, src/avram/validations.cr, src/lucky/ext/input_helpers.cr, src/lucky/ext/paginator/backend_helpers.cr
=> Support for Crystal 1.16

spec/avram/queryable_spec.cr, src/avram/queryable.cr
=> Adding nulls sorting to Queryable order_by.

spec/avram/queryable_spec.cr, src/avram/base_query_template.cr
=> Update `updated_at` column in `Avram::BaseQueryTemplate#update`

src/avram.cr, src/avram/callbacks/callbacks.cr, src/avram/callbacks/delete_callbacks.cr, src/avram/callbacks/save_callbacks.cr, src/avram/charms/bool_extensions.cr, src/avram/charms/enum_extensions.cr, src/avram/charms/float64_extensions.cr, src/avram/charms/int16_extensions.cr, src/avram/charms/int32_extensions.cr, src/avram/charms/int64_extensions.cr, src/avram/charms/json_extensions.cr, src/avram/charms/slice_extensions.cr, src/avram/charms/string_extensions.cr, src/avram/charms/time_extensions.cr, src/avram/charms/uuid_extensions.cr, src/lucky/ext/avram/errors.cr, src/lucky/ext/label_helpers.cr, src/lucky/ext/select_helpers.cr
=> Adds some missing types

shard.override.yml, shard.yml, src/avram/join.cr
=> Updating Wordsmith and fixing compilation error

src/avram/version.cr
=> Fix VERSION compilation error
